-- Phase 28 — Customer Support Intake, Incidents & Internal SLA Monitoring
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Canonical source record. Browser roles cannot directly access support/incident tables.

begin;

alter table public.tw_ops_cases
  drop constraint if exists tw_ops_cases_case_type_check;
alter table public.tw_ops_cases
  add constraint tw_ops_cases_case_type_check check (case_type in (
    'ach_return','payment_return','negative_balance','card_dispute','card_refund','provider_failure',
    'customer_support','account_access'
  ));

create table if not exists public.tw_support_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  request_key text not null unique,
  request_type text not null check (request_type in (
    'general','account_access','ach_transfer','bill_payment','card_purchase',
    'direct_deposit','card_dispute'
  )),
  subject text not null check (char_length(subject) between 3 and 160),
  resource_kind text,
  resource_ref text,
  provider text,
  priority text not null default 'normal' check (priority in ('normal','high')),
  state text not null default 'open' check (state in ('open','triaged','waiting_on_user','resolved','closed')),
  ops_case_id uuid references public.tw_ops_cases(id) on delete set null,
  assigned_to_staff_user_id uuid references auth.users(id) on delete set null,
  first_staff_response_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.tw_support_messages (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.tw_support_requests(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_kind text not null check (author_kind in ('user','staff','system')),
  author_user_id uuid references auth.users(id) on delete set null,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create table if not exists public.tw_ops_sla_policies (
  id uuid primary key default gen_random_uuid(),
  policy_version text not null unique,
  environment text not null check (environment in ('sandbox','production')),
  critical_alert_ack_minutes integer not null check (critical_alert_ack_minutes between 1 and 1440),
  high_alert_ack_minutes integer not null check (high_alert_ack_minutes between 1 and 2880),
  support_first_response_minutes integer not null check (support_first_response_minutes between 1 and 10080),
  risk_review_minutes integer not null check (risk_review_minutes between 1 and 10080),
  case_update_minutes integer not null check (case_update_minutes between 1 and 43200),
  active boolean not null default false,
  public_commitment boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_ops_incidents (
  id uuid primary key default gen_random_uuid(),
  incident_key text not null unique,
  title text not null check (char_length(title) between 3 and 160),
  component text not null check (component in (
    'auth','provider_gateway','money_gateway','provider_webhooks','risk_engine','ops','support','release'
  )),
  severity text not null check (severity in ('minor','major','critical')),
  state text not null default 'investigating' check (state in ('investigating','identified','monitoring','resolved')),
  safe_summary text not null check (char_length(safe_summary) between 1 and 2000),
  created_by_staff_user_id uuid not null references auth.users(id) on delete restrict,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.tw_ops_incident_events (
  id bigint generated by default as identity primary key,
  incident_id uuid not null references public.tw_ops_incidents(id) on delete cascade,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  event_type text not null,
  state text,
  safe_detail text check (safe_detail is null or char_length(safe_detail) <= 2000),
  created_at timestamptz not null default now()
);

create index if not exists tw_support_requests_user_state_idx on public.tw_support_requests(user_id,state,updated_at desc);
create index if not exists tw_support_requests_staff_idx on public.tw_support_requests(state,priority,created_at);
create index if not exists tw_support_messages_request_idx on public.tw_support_messages(request_id,id);
create index if not exists tw_ops_incidents_state_idx on public.tw_ops_incidents(state,severity,updated_at desc);
create index if not exists tw_ops_incident_events_incident_idx on public.tw_ops_incident_events(incident_id,id);

alter table public.tw_support_requests enable row level security;
alter table public.tw_support_messages enable row level security;
alter table public.tw_ops_sla_policies enable row level security;
alter table public.tw_ops_incidents enable row level security;
alter table public.tw_ops_incident_events enable row level security;

revoke all on table public.tw_support_requests,public.tw_support_messages,public.tw_ops_sla_policies,
  public.tw_ops_incidents,public.tw_ops_incident_events from public,anon,authenticated;
grant select,insert,update,delete on table public.tw_support_requests,public.tw_support_messages,public.tw_ops_sla_policies,
  public.tw_ops_incidents,public.tw_ops_incident_events to service_role;

drop trigger if exists tw_support_messages_immutable on public.tw_support_messages;
create trigger tw_support_messages_immutable
before update or delete on public.tw_support_messages
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_ops_incident_events_immutable on public.tw_ops_incident_events;
create trigger tw_ops_incident_events_immutable
before update or delete on public.tw_ops_incident_events
for each row execute function tw_internal.reject_money_history_mutation();

insert into public.tw_ops_sla_policies(
  policy_version,environment,critical_alert_ack_minutes,high_alert_ack_minutes,
  support_first_response_minutes,risk_review_minutes,case_update_minutes,active,public_commitment
) values ('2026-09-beta-v1','sandbox',15,60,240,240,1440,true,false)
on conflict (policy_version) do update set
  critical_alert_ack_minutes=excluded.critical_alert_ack_minutes,
  high_alert_ack_minutes=excluded.high_alert_ack_minutes,
  support_first_response_minutes=excluded.support_first_response_minutes,
  risk_review_minutes=excluded.risk_review_minutes,
  case_update_minutes=excluded.case_update_minutes,
  active=true,public_commitment=false,updated_at=now();

insert into public.tw_ops_sla_policies(
  policy_version,environment,critical_alert_ack_minutes,high_alert_ack_minutes,
  support_first_response_minutes,risk_review_minutes,case_update_minutes,active,public_commitment
) values ('production-template-v1','production',15,60,240,240,1440,false,false)
on conflict (policy_version) do update set active=false,public_commitment=false,updated_at=now();

-- Deployed service-role-only RPCs:
-- tw_support_create_request(...)
-- tw_support_add_user_message(...)
-- tw_support_staff_reply(...)
-- tw_support_staff_assign(...)

revoke all on function public.tw_support_create_request(uuid,text,text,text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.tw_support_create_request(uuid,text,text,text,text,text,text,text,text) to service_role;
revoke all on function public.tw_support_add_user_message(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.tw_support_add_user_message(uuid,uuid,text) to service_role;
revoke all on function public.tw_support_staff_reply(uuid,text,uuid,text,text) from public,anon,authenticated;
grant execute on function public.tw_support_staff_reply(uuid,text,uuid,text,text) to service_role;
revoke all on function public.tw_support_staff_assign(uuid,text,uuid) from public,anon,authenticated;
grant execute on function public.tw_support_staff_assign(uuid,text,uuid) to service_role;

commit;
