import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const need=(label,haystack,needle)=>{if(!haystack.includes(needle)){console.error('Missing '+label+': '+needle);process.exitCode=1;}};
const schema=read('supabase/phase34/controlled_staff_bootstrap.sql');
const summary=read('supabase/phase34/staff_role_summary_rpc.sql');
const gateway=read('supabase/functions/thisweek-staff-gateway/index.ts');
const html=read('ops/bootstrap/index.html');
const app=read('ops/bootstrap/app.js');
need('append-only staff role events',schema,'tw_ops_staff_role_events_immutable');
need('browser table access revoked',schema,'from public,anon,authenticated');
need('service-only staff role table policies',schema,'to service_role');
need('staff role summary RPC',summary,'tw_staff_role_summary');
need('staff user role RPC',summary,'tw_staff_user_role');
need('summary RPC browser revoke',summary,'from public,anon,authenticated');
need('server admin API',gateway,'auth.admin.updateUserById');
need('bootstrap allowlist secret',gateway,'THISWEEK_BOOTSTRAP_ADMIN_EMAIL');
need('bootstrap requires AAL2',gateway,'mfa_aal2_required');
need('server MFA AAL checks the presented JWT',gateway,'getAuthenticatorAssuranceLevel(token)');
need('bootstrap requires confirmed email',gateway,'confirmed_email_required');
need('bootstrap closes after staff exists',gateway,'staff_bootstrap_closed');
need('last admin protection',gateway,'last_admin_protected');
need('authoritative role lookup',gateway,'tw_staff_user_role');
need('active session check',gateway,'tw_auth_session_active');
need('role audit write',gateway,'tw_ops_staff_role_events');
need('no direct auth table mutation',gateway,'updateUserById');
if(/from\(["']auth\.users["']\)|update\s+auth\.users/i.test(gateway)){console.error('Direct auth.users mutation found');process.exitCode=1;}
need('bootstrap page title',html,'Staff Bootstrap');
need('bootstrap no automatic privilege warning',html,'No automatic privilege');
need('bootstrap gateway client',app,'/functions/v1/thisweek-staff-gateway');
need('shared tab auth session',app,'thisweek.auth.session.v1');
need('stale AAL1 refresh-token exchange',app,"/auth/v1/token?grant_type=refresh_token");
need('refreshed token persistence',app,'function writeSession(next)');
need('automatic page return refresh',app,"window.addEventListener('pageshow'");
need('bootstrap cache-busted client',html,'./app.js?v=phase34e');
need('release manifest evidence prefill',app,"fetch('../../release.json");
if(process.exitCode)process.exit(process.exitCode);
console.log('Phase 34c staff-bootstrap checks passed.');
