-- Phase 34 continuation — controlled staff bootstrap and role provisioning
-- Staff identities remain real Supabase Auth users. No browser role escalation.

begin;

create table if not exists public.tw_ops_staff_role_events (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references auth.users(id) on delete restrict,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (action in ('bootstrap_admin','set_role','revoke_role')),
  previous_role text check (previous_role is null or previous_role in ('support_ops','risk_ops','admin')),
  next_role text check (next_role is null or next_role in ('support_ops','risk_ops','admin')),
  reason_code text not null check (length(trim(reason_code)) between 3 and 120),
  evidence_ref text not null check (length(trim(evidence_ref)) between 3 and 500),
  safe_detail jsonb not null default '{}'::jsonb check (jsonb_typeof(safe_detail)='object'),
  created_at timestamptz not null default now(),
  check (previous_role is distinct from next_role)
);

alter table public.tw_ops_staff_role_events enable row level security;

revoke all on table public.tw_ops_staff_role_events from public,anon,authenticated;
grant select,insert on table public.tw_ops_staff_role_events to service_role;
grant usage,select on sequence public.tw_ops_staff_role_events_id_seq to service_role;

drop policy if exists tw_ops_staff_role_events_service_select on public.tw_ops_staff_role_events;
create policy tw_ops_staff_role_events_service_select
on public.tw_ops_staff_role_events
for select to service_role using (true);

drop policy if exists tw_ops_staff_role_events_service_insert on public.tw_ops_staff_role_events;
create policy tw_ops_staff_role_events_service_insert
on public.tw_ops_staff_role_events
for insert to service_role with check (true);

create index if not exists tw_ops_staff_role_events_target_idx
  on public.tw_ops_staff_role_events(target_user_id,id desc);
create index if not exists tw_ops_staff_role_events_actor_idx
  on public.tw_ops_staff_role_events(actor_user_id,id desc);
create index if not exists tw_ops_staff_role_events_created_idx
  on public.tw_ops_staff_role_events(created_at desc,id desc);

drop trigger if exists tw_ops_staff_role_events_immutable on public.tw_ops_staff_role_events;
create trigger tw_ops_staff_role_events_immutable
before update or delete on public.tw_ops_staff_role_events
for each row execute function tw_internal.reject_money_history_mutation();

commit;
