-- Phase 34 — Release Evidence & Sandbox Certification
-- Evidence is append-only. Production money remains governed by Phase 31's fail-closed interlock.

begin;

create table if not exists public.tw_release_certification_requirements (
  requirement_key text primary key,
  provider text,
  group_key text not null,
  label text not null,
  required_for_sandbox_e2e boolean not null default true,
  active boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now(),
  check (provider is null or provider in ('plaid','unit','pinwheel','method','thisweek'))
);

create table if not exists public.tw_release_certification_runs (
  id uuid primary key default gen_random_uuid(),
  environment text not null default 'sandbox' check (environment='sandbox'),
  release_candidate_sha text not null check (release_candidate_sha ~ '^[0-9a-f]{7,64}$'),
  checklist_version text not null default '2026-09-v1',
  started_by_staff_user_id uuid not null references auth.users(id) on delete restrict,
  note text,
  started_at timestamptz not null default now()
);

create table if not exists public.tw_release_drill_runs (
  id uuid primary key default gen_random_uuid(),
  drill_type text not null check (drill_type in ('synthetic_incident','rollback')),
  environment text not null default 'sandbox' check (environment='sandbox'),
  release_candidate_sha text not null check (release_candidate_sha ~ '^[0-9a-f]{7,64}$'),
  scenario_key text not null,
  started_by_staff_user_id uuid not null references auth.users(id) on delete restrict,
  note text,
  started_at timestamptz not null default now()
);

create table if not exists public.tw_release_drill_events (
  id bigint generated by default as identity primary key,
  drill_id uuid not null references public.tw_release_drill_runs(id) on delete restrict,
  event_type text not null check (event_type in ('started','step','completed','failed')),
  outcome text check (outcome is null or outcome in ('pass','fail')),
  evidence_ref text,
  safe_summary text,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  check (
    (event_type in ('completed','failed') and outcome in ('pass','fail') and length(trim(coalesce(evidence_ref,''))) >= 3)
    or
    (event_type in ('started','step'))
  )
);

create table if not exists public.tw_release_certification_receipts (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.tw_release_certification_runs(id) on delete restrict,
  requirement_key text not null references public.tw_release_certification_requirements(requirement_key) on delete restrict,
  outcome text not null check (outcome in ('pass','fail')),
  evidence_ref text not null check (length(trim(evidence_ref)) >= 3),
  safe_summary text,
  drill_id uuid references public.tw_release_drill_runs(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  supersedes_receipt_id bigint references public.tw_release_certification_receipts(id) on delete restrict,
  created_at timestamptz not null default now(),
  check (supersedes_receipt_id is null or supersedes_receipt_id <> id)
);

create table if not exists public.tw_release_gate_evidence_requirements (
  gate_key text not null references public.tw_release_gates(gate_key) on delete restrict,
  evidence_key text not null,
  label text not null,
  source_type text not null check (source_type in ('manual','derived')),
  sort_order integer not null default 100,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (gate_key,evidence_key)
);

create table if not exists public.tw_release_gate_evidence (
  id bigint generated by default as identity primary key,
  gate_key text not null,
  evidence_key text not null,
  environment text not null check (environment in ('sandbox','production')),
  provider text,
  outcome text not null check (outcome in ('pass','fail')),
  evidence_ref text not null check (length(trim(evidence_ref)) >= 3),
  safe_summary text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  supersedes_evidence_id bigint references public.tw_release_gate_evidence(id) on delete restrict,
  created_at timestamptz not null default now(),
  foreign key (gate_key,evidence_key)
    references public.tw_release_gate_evidence_requirements(gate_key,evidence_key) on delete restrict,
  check (provider is null or provider in ('plaid','unit','pinwheel','method','thisweek')),
  check (supersedes_evidence_id is null or supersedes_evidence_id <> id)
);

alter table public.tw_release_certification_requirements enable row level security;
alter table public.tw_release_certification_runs enable row level security;
alter table public.tw_release_drill_runs enable row level security;
alter table public.tw_release_drill_events enable row level security;
alter table public.tw_release_certification_receipts enable row level security;
alter table public.tw_release_gate_evidence_requirements enable row level security;
alter table public.tw_release_gate_evidence enable row level security;

revoke all on table
  public.tw_release_certification_requirements,
  public.tw_release_certification_runs,
  public.tw_release_drill_runs,
  public.tw_release_drill_events,
  public.tw_release_certification_receipts,
  public.tw_release_gate_evidence_requirements,
  public.tw_release_gate_evidence
from public,anon,authenticated;

grant select,insert,update,delete on table
  public.tw_release_certification_requirements,
  public.tw_release_gate_evidence_requirements
to service_role;

grant select,insert on table
  public.tw_release_certification_runs,
  public.tw_release_drill_runs,
  public.tw_release_drill_events,
  public.tw_release_certification_receipts,
  public.tw_release_gate_evidence
to service_role;

grant usage,select on sequence
  public.tw_release_drill_events_id_seq,
  public.tw_release_certification_receipts_id_seq,
  public.tw_release_gate_evidence_id_seq
to service_role;

create index if not exists tw_release_cert_runs_staff_idx
  on public.tw_release_certification_runs(started_by_staff_user_id,started_at desc);
create index if not exists tw_release_drill_runs_staff_idx
  on public.tw_release_drill_runs(started_by_staff_user_id,started_at desc);
create index if not exists tw_release_drill_events_drill_idx
  on public.tw_release_drill_events(drill_id,id desc);
create index if not exists tw_release_drill_events_staff_idx
  on public.tw_release_drill_events(staff_user_id,id desc);
create index if not exists tw_release_cert_receipts_run_idx
  on public.tw_release_certification_receipts(run_id,requirement_key,id desc);
create index if not exists tw_release_cert_receipts_requirement_idx
  on public.tw_release_certification_receipts(requirement_key,id desc);
create index if not exists tw_release_cert_receipts_drill_idx
  on public.tw_release_certification_receipts(drill_id) where drill_id is not null;
create index if not exists tw_release_cert_receipts_staff_idx
  on public.tw_release_certification_receipts(staff_user_id,id desc);
create index if not exists tw_release_cert_receipts_supersedes_idx
  on public.tw_release_certification_receipts(supersedes_receipt_id) where supersedes_receipt_id is not null;
create index if not exists tw_release_gate_evidence_gate_idx
  on public.tw_release_gate_evidence(gate_key,evidence_key,id desc);
create index if not exists tw_release_gate_evidence_staff_idx
  on public.tw_release_gate_evidence(staff_user_id,id desc);
create index if not exists tw_release_gate_evidence_supersedes_idx
  on public.tw_release_gate_evidence(supersedes_evidence_id) where supersedes_evidence_id is not null;

drop trigger if exists tw_release_certification_runs_immutable on public.tw_release_certification_runs;
create trigger tw_release_certification_runs_immutable
before update or delete on public.tw_release_certification_runs
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_release_drill_runs_immutable on public.tw_release_drill_runs;
create trigger tw_release_drill_runs_immutable
before update or delete on public.tw_release_drill_runs
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_release_drill_events_immutable on public.tw_release_drill_events;
create trigger tw_release_drill_events_immutable
before update or delete on public.tw_release_drill_events
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_release_certification_receipts_immutable on public.tw_release_certification_receipts;
create trigger tw_release_certification_receipts_immutable
before update or delete on public.tw_release_certification_receipts
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_release_gate_evidence_immutable on public.tw_release_gate_evidence;
create trigger tw_release_gate_evidence_immutable
before update or delete on public.tw_release_gate_evidence
for each row execute function tw_internal.reject_money_history_mutation();

insert into public.tw_release_certification_requirements
(requirement_key,provider,group_key,label,required_for_sandbox_e2e,active,sort_order)
values
  ('provider_preflight','thisweek','provider','Provider credential preflight reports credential_valid',true,true,10),
  ('sandbox_webhook_registration','thisweek','provider','Sandbox provider webhooks registered and verified',true,true,20),
  ('plaid_bank_connection','plaid','provider','Plaid Sandbox bank connection completed',true,true,30),
  ('unit_onboarding_account','unit','provider','Unit Sandbox onboarding and deposit account completed',true,true,40),
  ('ach_funding','unit','money','Sandbox ACH funding completed and ledger reconciled',true,true,50),
  ('card_issue','unit','card','Sandbox virtual card issued',true,true,60),
  ('card_authorization_hold','unit','card','Authorization produced the expected envelope hold',true,true,70),
  ('card_settlement','unit','card','Settlement posted correctly without rewriting history',true,true,80),
  ('card_reversal','unit','card','Reversal released or compensated correctly',true,true,90),
  ('pinwheel_direct_deposit_switch','pinwheel','provider','Pinwheel Sandbox direct-deposit switch completed',true,true,100),
  ('method_bill_payment','method','provider','Method dev bill payment completed',true,true,110),
  ('ach_return_lifecycle','unit','adverse','ACH return / negative-balance lifecycle validated',true,true,120),
  ('card_dispute_refund','unit','adverse','Card dispute/refund lifecycle validated',true,true,130),
  ('synthetic_incident_drill','thisweek','operations','Synthetic incident drill completed successfully',true,true,140),
  ('rollback_validation','thisweek','operations','Rollback procedure validated against the release candidate',true,true,150)
on conflict (requirement_key) do update set
  provider=excluded.provider,
  group_key=excluded.group_key,
  label=excluded.label,
  required_for_sandbox_e2e=excluded.required_for_sandbox_e2e,
  active=excluded.active,
  sort_order=excluded.sort_order,
  updated_at=now();

insert into public.tw_release_gate_evidence_requirements
(gate_key,evidence_key,label,source_type,sort_order,active)
values
  ('hosted_auth_production_ready','auth_site_url','Canonical production Site URL verified','manual',10,true),
  ('hosted_auth_production_ready','auth_redirect_allowlist','Exact production redirect allowlist verified','manual',20,true),
  ('hosted_auth_production_ready','auth_email_confirmation','Email confirmation behavior verified','manual',30,true),
  ('hosted_auth_production_ready','auth_captcha','CAPTCHA/bot protection verified','manual',40,true),
  ('hosted_auth_production_ready','auth_smtp','Production SMTP/mail delivery verified','manual',50,true),
  ('hosted_auth_production_ready','auth_recovery_flow','Recovery flow delivery and redirect verified','manual',60,true),

  ('provider_sandbox_e2e_passed','sandbox_certification_passed','Latest Sandbox certification run is fully passed','derived',10,true),
  ('provider_sandbox_e2e_passed','rollback_drill_passed','Rollback drill passed for a release candidate','derived',20,true),

  ('production_provider_approvals','provider_program_approvals','Provider/banking program production approvals evidenced','manual',10,true),

  ('production_webhooks_verified','webhook_plaid','Plaid production webhook registration verified','manual',10,true),
  ('production_webhooks_verified','webhook_unit','Unit production webhook registration verified','manual',20,true),
  ('production_webhooks_verified','webhook_pinwheel','Pinwheel production webhook registration verified','manual',30,true),
  ('production_webhooks_verified','webhook_method','Method production webhook registration verified','manual',40,true),

  ('production_risk_policy_approved','production_risk_review','Production risk limits reviewed and approved','manual',10,true),
  ('production_risk_policy_approved','production_risk_policy_active','Production risk policy is currently active','derived',20,true),

  ('named_staff_provisioned','staff_coverage_review','Named least-privilege staff coverage reviewed','manual',10,true),
  ('named_staff_provisioned','staff_coverage_current','Admin, risk and support coverage currently exists','derived',20,true),

  ('external_notification_delivery_verified','notification_delivery_receipt','External critical notification delivery receipt recorded','manual',10,true),
  ('external_notification_delivery_verified','notification_channel_healthy','External notification channel is currently healthy','derived',20,true),

  ('incident_escalation_runbook_approved','incident_runbook_approval','Incident/provider escalation runbook approved','manual',10,true),
  ('incident_escalation_runbook_approved','synthetic_incident_drill_passed','Synthetic incident drill has passed','derived',20,true),

  ('retention_access_policy_approved','retention_policy_approval','Retention/access-log policy approval evidenced','manual',10,true),
  ('retention_access_policy_approved','production_retention_policy_active','Approved production retention policy is active','derived',20,true),
  ('retention_access_policy_approved','sensitive_access_audit_active','Sensitive staff-access audit has been exercised','derived',30,true),

  ('legal_terms_privacy_approved','legal_approval','Production terms/privacy/disclosures approval evidenced','manual',10,true),
  ('legal_terms_privacy_approved','production_legal_set_active','Approved production legal set is active','derived',20,true),

  ('cost_approval','cost_approval_receipt','Provider/program production costs explicitly approved','manual',10,true)
on conflict (gate_key,evidence_key) do update set
  label=excluded.label,
  source_type=excluded.source_type,
  sort_order=excluded.sort_order,
  active=excluded.active,
  updated_at=now();

create or replace function public.tw_release_drill_status(p_drill_id uuid)
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  with d as (
    select * from public.tw_release_drill_runs where id=p_drill_id
  ),
  terminal as (
    select e.*
    from public.tw_release_drill_events e
    where e.drill_id=p_drill_id and e.event_type in ('completed','failed')
    order by e.id desc limit 1
  )
  select case when not exists(select 1 from d) then
    jsonb_build_object('exists',false,'passed',false)
  else
    jsonb_build_object(
      'exists',true,
      'drillId',(select id from d),
      'drillType',(select drill_type from d),
      'releaseCandidateSha',(select release_candidate_sha from d),
      'terminal',exists(select 1 from terminal),
      'passed',coalesce((select outcome='pass' and event_type='completed' from terminal),false),
      'terminalEventId',(select id from terminal),
      'evidenceRef',(select evidence_ref from terminal)
    )
  end;
$$;

create or replace function public.tw_release_start_drill(
  p_staff_user_id uuid,
  p_drill_type text,
  p_release_candidate_sha text,
  p_scenario_key text,
  p_note text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id uuid;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;
  if p_drill_type not in ('synthetic_incident','rollback') then raise exception 'invalid_drill_type'; end if;
  if coalesce(p_release_candidate_sha,'') !~ '^[0-9a-f]{7,64}$' then raise exception 'invalid_release_candidate_sha'; end if;
  if length(trim(coalesce(p_scenario_key,''))) < 3 then raise exception 'drill_scenario_required'; end if;

  insert into public.tw_release_drill_runs(
    drill_type,release_candidate_sha,scenario_key,started_by_staff_user_id,note
  ) values (
    p_drill_type,lower(p_release_candidate_sha),left(trim(p_scenario_key),120),p_staff_user_id,
    left(nullif(trim(coalesce(p_note,'')),''),1000)
  ) returning id into v_id;

  insert into public.tw_release_drill_events(
    drill_id,event_type,outcome,evidence_ref,safe_summary,staff_user_id
  ) values (v_id,'started',null,null,'drill_started',p_staff_user_id);

  return v_id;
end;
$$;

create or replace function public.tw_release_finish_drill(
  p_staff_user_id uuid,
  p_drill_id uuid,
  p_passed boolean,
  p_evidence_ref text,
  p_safe_summary text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;
  if not exists(select 1 from public.tw_release_drill_runs where id=p_drill_id) then raise exception 'drill_not_found'; end if;
  if exists(select 1 from public.tw_release_drill_events where drill_id=p_drill_id and event_type in ('completed','failed')) then
    raise exception 'drill_already_terminal';
  end if;
  if length(trim(coalesce(p_evidence_ref,''))) < 3 then raise exception 'drill_evidence_required'; end if;

  insert into public.tw_release_drill_events(
    drill_id,event_type,outcome,evidence_ref,safe_summary,staff_user_id
  ) values (
    p_drill_id,
    case when p_passed then 'completed' else 'failed' end,
    case when p_passed then 'pass' else 'fail' end,
    left(trim(p_evidence_ref),500),
    left(nullif(trim(coalesce(p_safe_summary,'')),''),1000),
    p_staff_user_id
  );

  return public.tw_release_drill_status(p_drill_id);
end;
$$;

create or replace function public.tw_release_start_certification(
  p_staff_user_id uuid,
  p_release_candidate_sha text,
  p_note text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id uuid;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;
  if coalesce(p_release_candidate_sha,'') !~ '^[0-9a-f]{7,64}$' then raise exception 'invalid_release_candidate_sha'; end if;

  insert into public.tw_release_certification_runs(
    release_candidate_sha,started_by_staff_user_id,note
  ) values (
    lower(p_release_candidate_sha),p_staff_user_id,left(nullif(trim(coalesce(p_note,'')),''),1000)
  ) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.tw_release_record_certification_receipt(
  p_staff_user_id uuid,
  p_run_id uuid,
  p_requirement_key text,
  p_outcome text,
  p_evidence_ref text,
  p_safe_summary text default null,
  p_drill_id uuid default null,
  p_metadata jsonb default '{}'::jsonb,
  p_supersedes_receipt_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id bigint;
  v_req public.tw_release_certification_requirements%rowtype;
  v_drill jsonb;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;
  if not exists(select 1 from public.tw_release_certification_runs where id=p_run_id) then raise exception 'certification_run_not_found'; end if;
  select * into v_req from public.tw_release_certification_requirements
  where requirement_key=p_requirement_key and active=true;
  if v_req.requirement_key is null then raise exception 'certification_requirement_not_found'; end if;
  if p_outcome not in ('pass','fail') then raise exception 'invalid_certification_outcome'; end if;
  if length(trim(coalesce(p_evidence_ref,''))) < 3 then raise exception 'certification_evidence_required'; end if;
  if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' then raise exception 'certification_metadata_must_be_object'; end if;

  if p_requirement_key in ('synthetic_incident_drill','rollback_validation') and p_outcome='pass' then
    if p_drill_id is null then raise exception 'passing_drill_receipt_required'; end if;
    v_drill:=public.tw_release_drill_status(p_drill_id);
    if coalesce((v_drill->>'passed')::boolean,false) is not true then raise exception 'passing_drill_receipt_required'; end if;
    if p_requirement_key='synthetic_incident_drill' and v_drill->>'drillType' <> 'synthetic_incident' then raise exception 'wrong_drill_type'; end if;
    if p_requirement_key='rollback_validation' and v_drill->>'drillType' <> 'rollback' then raise exception 'wrong_drill_type'; end if;
  end if;

  if p_supersedes_receipt_id is not null and not exists(
    select 1 from public.tw_release_certification_receipts
    where id=p_supersedes_receipt_id and run_id=p_run_id and requirement_key=p_requirement_key
  ) then raise exception 'superseded_receipt_mismatch'; end if;

  insert into public.tw_release_certification_receipts(
    run_id,requirement_key,outcome,evidence_ref,safe_summary,drill_id,metadata,staff_user_id,supersedes_receipt_id
  ) values (
    p_run_id,p_requirement_key,p_outcome,left(trim(p_evidence_ref),500),
    left(nullif(trim(coalesce(p_safe_summary,'')),''),1000),p_drill_id,p_metadata,p_staff_user_id,p_supersedes_receipt_id
  ) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.tw_release_certification_status(p_run_id uuid)
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  with req as (
    select * from public.tw_release_certification_requirements
    where active=true and required_for_sandbox_e2e=true
  ),
  latest as (
    select distinct on (r.requirement_key)
      r.requirement_key,r.outcome,r.evidence_ref,r.drill_id,r.created_at,r.id
    from public.tw_release_certification_receipts r
    where r.run_id=p_run_id
    order by r.requirement_key,r.created_at desc,r.id desc
  ),
  rows as (
    select
      q.requirement_key,q.provider,q.group_key,q.label,q.sort_order,
      l.outcome,l.evidence_ref,l.drill_id,l.created_at,l.id as receipt_id,
      coalesce(l.outcome='pass',false) as passed
    from req q left join latest l using(requirement_key)
  ),
  run as (
    select * from public.tw_release_certification_runs where id=p_run_id
  )
  select case when not exists(select 1 from run) then
    jsonb_build_object('exists',false,'passed',false)
  else jsonb_build_object(
    'exists',true,
    'runId',(select id from run),
    'releaseCandidateSha',(select release_candidate_sha from run),
    'checklistVersion',(select checklist_version from run),
    'requiredCount',(select count(*) from rows),
    'passedCount',(select count(*) from rows where passed),
    'failedCount',(select count(*) from rows where outcome='fail'),
    'missing',coalesce((select jsonb_agg(requirement_key order by sort_order) from rows where outcome is null),'[]'::jsonb),
    'passed',coalesce((select bool_and(passed) from rows),false) and exists(select 1 from rows),
    'requirements',coalesce((select jsonb_agg(jsonb_build_object(
      'requirementKey',requirement_key,'provider',provider,'group',group_key,'label',label,
      'outcome',outcome,'evidenceRef',evidence_ref,'drillId',drill_id,'receiptId',receipt_id,'recordedAt',created_at
    ) order by sort_order) from rows),'[]'::jsonb)
  ) end;
$$;

create or replace function public.tw_release_record_gate_evidence(
  p_staff_user_id uuid,
  p_gate_key text,
  p_evidence_key text,
  p_environment text,
  p_outcome text,
  p_evidence_ref text,
  p_safe_summary text default null,
  p_provider text default null,
  p_metadata jsonb default '{}'::jsonb,
  p_supersedes_evidence_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_source text;
  v_id bigint;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role is distinct from 'admin' then raise exception 'admin_role_required'; end if;

  select source_type into v_source
  from public.tw_release_gate_evidence_requirements
  where gate_key=p_gate_key and evidence_key=p_evidence_key and active=true;
  if v_source is null then raise exception 'release_evidence_requirement_not_found'; end if;
  if v_source <> 'manual' then raise exception 'derived_evidence_cannot_be_manually_recorded'; end if;
  if p_environment not in ('sandbox','production') then raise exception 'invalid_evidence_environment'; end if;
  if p_outcome not in ('pass','fail') then raise exception 'invalid_evidence_outcome'; end if;
  if length(trim(coalesce(p_evidence_ref,''))) < 3 then raise exception 'release_evidence_ref_required'; end if;
  if p_provider is not null and p_provider not in ('plaid','unit','pinwheel','method','thisweek') then raise exception 'invalid_evidence_provider'; end if;
  if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' then raise exception 'release_evidence_metadata_must_be_object'; end if;

  if p_supersedes_evidence_id is not null and not exists(
    select 1 from public.tw_release_gate_evidence
    where id=p_supersedes_evidence_id and gate_key=p_gate_key and evidence_key=p_evidence_key
  ) then raise exception 'superseded_evidence_mismatch'; end if;

  insert into public.tw_release_gate_evidence(
    gate_key,evidence_key,environment,provider,outcome,evidence_ref,safe_summary,metadata,
    staff_user_id,supersedes_evidence_id
  ) values (
    p_gate_key,p_evidence_key,p_environment,p_provider,p_outcome,left(trim(p_evidence_ref),500),
    left(nullif(trim(coalesce(p_safe_summary,'')),''),1000),p_metadata,p_staff_user_id,p_supersedes_evidence_id
  ) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.tw_release_derived_evidence_pass(p_evidence_key text)
returns boolean
language plpgsql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
declare
  v_status jsonb;
begin
  if p_evidence_key='sandbox_certification_passed' then
    return exists(
      select 1 from public.tw_release_certification_runs r
      where coalesce((public.tw_release_certification_status(r.id)->>'passed')::boolean,false)=true
    );
  elsif p_evidence_key='rollback_drill_passed' then
    return exists(
      select 1 from public.tw_release_drill_runs d
      where d.drill_type='rollback'
        and coalesce((public.tw_release_drill_status(d.id)->>'passed')::boolean,false)=true
    );
  elsif p_evidence_key='synthetic_incident_drill_passed' then
    return exists(
      select 1 from public.tw_release_drill_runs d
      where d.drill_type='synthetic_incident'
        and coalesce((public.tw_release_drill_status(d.id)->>'passed')::boolean,false)=true
    );
  elsif p_evidence_key='staff_coverage_current' then
    return
      exists(select 1 from auth.users where coalesce(raw_app_meta_data->>'thisweek_role','')='admin')
      and exists(select 1 from auth.users where coalesce(raw_app_meta_data->>'thisweek_role','') in ('risk_ops','admin'))
      and exists(select 1 from auth.users where coalesce(raw_app_meta_data->>'thisweek_role','') in ('support_ops','admin'));
  elsif p_evidence_key='notification_channel_healthy' then
    return exists(
      select 1 from public.tw_ops_notification_channel_status
      where channel_key='external_webhook' and configured=true and state='healthy'
    );
  elsif p_evidence_key='production_risk_policy_active' then
    return exists(select 1 from public.tw_risk_policies where environment='production' and active=true);
  elsif p_evidence_key in ('production_legal_set_active','production_retention_policy_active','sensitive_access_audit_active') then
    v_status:=public.tw_release_status();
    if p_evidence_key='production_legal_set_active' then
      return coalesce((v_status->>'productionLegalSetActive')::boolean,false);
    elsif p_evidence_key='production_retention_policy_active' then
      return coalesce((v_status->>'productionRetentionPolicyActive')::boolean,false);
    else
      return coalesce((v_status->>'sensitiveAccessAuditActive')::boolean,false);
    end if;
  end if;
  return false;
end;
$$;

create or replace function public.tw_release_gate_evidence_status(p_gate_key text)
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  with req as (
    select *
    from public.tw_release_gate_evidence_requirements
    where gate_key=p_gate_key and active=true
  ),
  latest_manual as (
    select distinct on (e.evidence_key)
      e.evidence_key,e.outcome,e.evidence_ref,e.created_at,e.id
    from public.tw_release_gate_evidence e
    where e.gate_key=p_gate_key
    order by e.evidence_key,e.created_at desc,e.id desc
  ),
  evaluated as (
    select
      r.evidence_key,r.label,r.source_type,r.sort_order,
      case
        when r.source_type='derived' then public.tw_release_derived_evidence_pass(r.evidence_key)
        else coalesce(m.outcome='pass',false)
      end as satisfied,
      m.outcome,m.evidence_ref,m.created_at,m.id
    from req r left join latest_manual m using(evidence_key)
  )
  select jsonb_build_object(
    'gateKey',p_gate_key,
    'requiredCount',(select count(*) from evaluated),
    'satisfiedCount',(select count(*) from evaluated where satisfied),
    'ready',coalesce((select bool_and(satisfied) from evaluated),false) and exists(select 1 from evaluated),
    'requirements',coalesce((select jsonb_agg(jsonb_build_object(
      'evidenceKey',evidence_key,'label',label,'sourceType',source_type,'satisfied',satisfied,
      'outcome',outcome,'evidenceRef',evidence_ref,'recordedAt',created_at,'receiptId',id
    ) order by sort_order) from evaluated),'[]'::jsonb)
  );
$$;

create or replace function public.tw_release_readiness_report()
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  with gates as (
    select
      g.gate_key,g.category,g.label,g.required_for_live_money,g.verified,g.verified_at,g.evidence_ref,
      public.tw_release_gate_evidence_status(g.gate_key) as evidence
    from public.tw_release_gates g
    order by g.category,g.gate_key
  ),
  latest_cert as (
    select r.*,public.tw_release_certification_status(r.id) as status
    from public.tw_release_certification_runs r
    order by r.started_at desc
    limit 1
  )
  select jsonb_build_object(
    'generatedAt',now(),
    'releaseStatus',public.tw_release_status(),
    'latestSandboxCertification',(select status from latest_cert),
    'gates',coalesce((select jsonb_agg(jsonb_build_object(
      'gateKey',gate_key,'category',category,'label',label,'required',required_for_live_money,
      'verified',verified,'verifiedAt',verified_at,'evidenceRef',evidence_ref,'evidence',evidence
    )) from gates),'[]'::jsonb),
    'blockingGateKeys',coalesce((select jsonb_agg(gate_key) from gates
      where required_for_live_money and (verified=false or coalesce((evidence->>'ready')::boolean,false)=false)
    ),'[]'::jsonb)
  );
$$;

create or replace function public.tw_release_set_gate(
  p_staff_user_id uuid,
  p_gate_key text,
  p_verified boolean,
  p_evidence_ref text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_gate public.tw_release_gates%rowtype;
  v_role text;
  v_evidence jsonb;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','')
  into v_role
  from auth.users
  where id=p_staff_user_id;

  if v_role is distinct from 'admin' then
    raise exception 'admin_role_required';
  end if;

  select * into v_gate
  from public.tw_release_gates
  where gate_key=p_gate_key
  for update;

  if v_gate.gate_key is null then raise exception 'release_gate_not_found'; end if;
  if coalesce(length(trim(p_evidence_ref)),0)<3 then raise exception 'release_gate_evidence_required'; end if;

  if p_verified then
    v_evidence:=public.tw_release_gate_evidence_status(p_gate_key);
    if coalesce((v_evidence->>'ready')::boolean,false) is not true then
      raise exception 'release_gate_supporting_evidence_missing';
    end if;
  end if;

  insert into public.tw_release_gate_events(
    gate_key,staff_user_id,previous_verified,next_verified,evidence_ref,note
  ) values (
    v_gate.gate_key,p_staff_user_id,v_gate.verified,p_verified,
    left(trim(p_evidence_ref),500),left(nullif(trim(coalesce(p_note,'')),''),1000)
  );

  update public.tw_release_gates
  set verified=p_verified,
      verified_by_staff_user_id=p_staff_user_id,
      verified_at=case when p_verified then now() else null end,
      evidence_ref=left(trim(p_evidence_ref),500),
      note=left(nullif(trim(coalesce(p_note,'')),''),1000),
      updated_at=now()
  where gate_key=v_gate.gate_key;

  return jsonb_build_object(
    'gateKey',v_gate.gate_key,
    'verified',p_verified,
    'supportingEvidence',v_evidence,
    'updatedBy',p_staff_user_id,
    'updatedAt',now()
  );
end;
$$;

revoke all on function public.tw_release_drill_status(uuid) from public,anon,authenticated;
revoke all on function public.tw_release_start_drill(uuid,text,text,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_finish_drill(uuid,uuid,boolean,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_start_certification(uuid,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_record_certification_receipt(uuid,uuid,text,text,text,text,uuid,jsonb,bigint) from public,anon,authenticated;
revoke all on function public.tw_release_certification_status(uuid) from public,anon,authenticated;
revoke all on function public.tw_release_record_gate_evidence(uuid,text,text,text,text,text,text,text,jsonb,bigint) from public,anon,authenticated;
revoke all on function public.tw_release_derived_evidence_pass(text) from public,anon,authenticated;
revoke all on function public.tw_release_gate_evidence_status(text) from public,anon,authenticated;
revoke all on function public.tw_release_readiness_report() from public,anon,authenticated;
revoke all on function public.tw_release_set_gate(uuid,text,boolean,text,text) from public,anon,authenticated;

grant execute on function public.tw_release_drill_status(uuid) to service_role;
grant execute on function public.tw_release_start_drill(uuid,text,text,text,text) to service_role;
grant execute on function public.tw_release_finish_drill(uuid,uuid,boolean,text,text) to service_role;
grant execute on function public.tw_release_start_certification(uuid,text,text) to service_role;
grant execute on function public.tw_release_record_certification_receipt(uuid,uuid,text,text,text,text,uuid,jsonb,bigint) to service_role;
grant execute on function public.tw_release_certification_status(uuid) to service_role;
grant execute on function public.tw_release_record_gate_evidence(uuid,text,text,text,text,text,text,text,jsonb,bigint) to service_role;
grant execute on function public.tw_release_derived_evidence_pass(text) to service_role;
grant execute on function public.tw_release_gate_evidence_status(text) to service_role;
grant execute on function public.tw_release_readiness_report() to service_role;
grant execute on function public.tw_release_set_gate(uuid,text,boolean,text,text) to service_role;

commit;
