-- Phase 34 continuation — release-candidate binding
-- Prevent historical certification/drill evidence from satisfying a newer release candidate.

begin;

create table if not exists public.tw_release_candidate_selections (
  id bigint generated by default as identity primary key,
  release_candidate_sha text not null check (release_candidate_sha ~ '^[0-9a-f]{40}$'),
  source_ref text not null check (length(trim(source_ref)) >= 3),
  note text,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

alter table public.tw_release_candidate_selections enable row level security;
revoke all on table public.tw_release_candidate_selections from public,anon,authenticated;
grant select,insert on table public.tw_release_candidate_selections to service_role;
grant usage,select on sequence public.tw_release_candidate_selections_id_seq to service_role;

drop policy if exists tw_release_candidate_selections_service_select on public.tw_release_candidate_selections;
create policy tw_release_candidate_selections_service_select
on public.tw_release_candidate_selections
for select to service_role using (true);

drop policy if exists tw_release_candidate_selections_service_insert on public.tw_release_candidate_selections;
create policy tw_release_candidate_selections_service_insert
on public.tw_release_candidate_selections
for insert to service_role with check (true);

create index if not exists tw_release_candidate_selections_created_idx
  on public.tw_release_candidate_selections(created_at desc,id desc);
create index if not exists tw_release_candidate_selections_staff_idx
  on public.tw_release_candidate_selections(staff_user_id,created_at desc);

drop trigger if exists tw_release_candidate_selections_immutable on public.tw_release_candidate_selections;
create trigger tw_release_candidate_selections_immutable
before update or delete on public.tw_release_candidate_selections
for each row execute function tw_internal.reject_money_history_mutation();

create or replace function public.tw_release_active_candidate()
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  select coalesce((
    select jsonb_build_object(
      'selectionId',s.id,
      'releaseCandidateSha',s.release_candidate_sha,
      'sourceRef',s.source_ref,
      'note',s.note,
      'selectedBy',s.staff_user_id,
      'selectedAt',s.created_at
    )
    from public.tw_release_candidate_selections s
    order by s.created_at desc,s.id desc
    limit 1
  ), jsonb_build_object(
    'selectionId',null,
    'releaseCandidateSha',null,
    'sourceRef',null,
    'note',null,
    'selectedBy',null,
    'selectedAt',null
  ));
$$;

create or replace function public.tw_release_select_candidate(
  p_staff_user_id uuid,
  p_release_candidate_sha text,
  p_source_ref text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id bigint;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;

  if v_role not in ('risk_ops','admin') then
    raise exception 'risk_or_admin_role_required';
  end if;
  if coalesce(lower(trim(p_release_candidate_sha)),'') !~ '^[0-9a-f]{40}$' then
    raise exception 'full_release_candidate_sha_required';
  end if;
  if length(trim(coalesce(p_source_ref,''))) < 3 then
    raise exception 'release_candidate_source_ref_required';
  end if;

  insert into public.tw_release_candidate_selections(
    release_candidate_sha,source_ref,note,staff_user_id
  ) values (
    lower(trim(p_release_candidate_sha)),
    left(trim(p_source_ref),500),
    left(nullif(trim(coalesce(p_note,'')),''),1000),
    p_staff_user_id
  ) returning id into v_id;

  return public.tw_release_active_candidate();
end;
$$;

create or replace function public.tw_release_start_certification(
  p_staff_user_id uuid,
  p_release_candidate_sha text,
  p_note text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id uuid;
  v_active_sha text;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;

  v_active_sha:=public.tw_release_active_candidate()->>'releaseCandidateSha';
  if v_active_sha is null then raise exception 'active_release_candidate_required'; end if;
  if lower(trim(coalesce(p_release_candidate_sha,''))) <> v_active_sha then
    raise exception 'release_candidate_mismatch';
  end if;

  insert into public.tw_release_certification_runs(
    release_candidate_sha,started_by_staff_user_id,note
  ) values (
    v_active_sha,p_staff_user_id,left(nullif(trim(coalesce(p_note,'')),''),1000)
  ) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.tw_release_start_drill(
  p_staff_user_id uuid,
  p_drill_type text,
  p_release_candidate_sha text,
  p_scenario_key text,
  p_note text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id uuid;
  v_active_sha text;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;
  if p_drill_type not in ('synthetic_incident','rollback') then raise exception 'invalid_drill_type'; end if;
  if length(trim(coalesce(p_scenario_key,''))) < 3 then raise exception 'drill_scenario_required'; end if;

  v_active_sha:=public.tw_release_active_candidate()->>'releaseCandidateSha';
  if v_active_sha is null then raise exception 'active_release_candidate_required'; end if;
  if lower(trim(coalesce(p_release_candidate_sha,''))) <> v_active_sha then
    raise exception 'release_candidate_mismatch';
  end if;

  insert into public.tw_release_drill_runs(
    drill_type,release_candidate_sha,scenario_key,started_by_staff_user_id,note
  ) values (
    p_drill_type,v_active_sha,left(trim(p_scenario_key),120),p_staff_user_id,
    left(nullif(trim(coalesce(p_note,'')),''),1000)
  ) returning id into v_id;

  insert into public.tw_release_drill_events(
    drill_id,event_type,outcome,evidence_ref,safe_summary,staff_user_id
  ) values (v_id,'started',null,null,'drill_started',p_staff_user_id);

  return v_id;
end;
$$;

create or replace function public.tw_release_finish_drill(
  p_staff_user_id uuid,
  p_drill_id uuid,
  p_passed boolean,
  p_evidence_ref text,
  p_safe_summary text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_active_sha text;
  v_drill_sha text;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;

  select release_candidate_sha into v_drill_sha
  from public.tw_release_drill_runs where id=p_drill_id;
  if v_drill_sha is null then raise exception 'drill_not_found'; end if;

  v_active_sha:=public.tw_release_active_candidate()->>'releaseCandidateSha';
  if v_active_sha is null or v_drill_sha <> v_active_sha then
    raise exception 'release_candidate_mismatch';
  end if;
  if exists(select 1 from public.tw_release_drill_events where drill_id=p_drill_id and event_type in ('completed','failed')) then
    raise exception 'drill_already_terminal';
  end if;
  if length(trim(coalesce(p_evidence_ref,''))) < 3 then raise exception 'drill_evidence_required'; end if;

  insert into public.tw_release_drill_events(
    drill_id,event_type,outcome,evidence_ref,safe_summary,staff_user_id
  ) values (
    p_drill_id,
    case when p_passed then 'completed' else 'failed' end,
    case when p_passed then 'pass' else 'fail' end,
    left(trim(p_evidence_ref),500),
    left(nullif(trim(coalesce(p_safe_summary,'')),''),1000),
    p_staff_user_id
  );

  return public.tw_release_drill_status(p_drill_id);
end;
$$;

create or replace function public.tw_release_record_certification_receipt(
  p_staff_user_id uuid,
  p_run_id uuid,
  p_requirement_key text,
  p_outcome text,
  p_evidence_ref text,
  p_safe_summary text default null,
  p_drill_id uuid default null,
  p_metadata jsonb default '{}'::jsonb,
  p_supersedes_receipt_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_role text;
  v_id bigint;
  v_req public.tw_release_certification_requirements%rowtype;
  v_drill jsonb;
  v_active_sha text;
  v_run_sha text;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','') into v_role
  from auth.users where id=p_staff_user_id;
  if v_role not in ('risk_ops','admin') then raise exception 'risk_or_admin_role_required'; end if;

  select release_candidate_sha into v_run_sha
  from public.tw_release_certification_runs where id=p_run_id;
  if v_run_sha is null then raise exception 'certification_run_not_found'; end if;

  v_active_sha:=public.tw_release_active_candidate()->>'releaseCandidateSha';
  if v_active_sha is null or v_run_sha <> v_active_sha then
    raise exception 'release_candidate_mismatch';
  end if;

  select * into v_req from public.tw_release_certification_requirements
  where requirement_key=p_requirement_key and active=true;
  if v_req.requirement_key is null then raise exception 'certification_requirement_not_found'; end if;
  if p_outcome not in ('pass','fail') then raise exception 'invalid_certification_outcome'; end if;
  if length(trim(coalesce(p_evidence_ref,''))) < 3 then raise exception 'certification_evidence_required'; end if;
  if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' then raise exception 'certification_metadata_must_be_object'; end if;

  if p_requirement_key in ('synthetic_incident_drill','rollback_validation') and p_outcome='pass' then
    if p_drill_id is null then raise exception 'passing_drill_receipt_required'; end if;
    v_drill:=public.tw_release_drill_status(p_drill_id);
    if coalesce((v_drill->>'passed')::boolean,false) is not true then raise exception 'passing_drill_receipt_required'; end if;
    if v_drill->>'releaseCandidateSha' <> v_active_sha then raise exception 'release_candidate_mismatch'; end if;
    if p_requirement_key='synthetic_incident_drill' and v_drill->>'drillType' <> 'synthetic_incident' then raise exception 'wrong_drill_type'; end if;
    if p_requirement_key='rollback_validation' and v_drill->>'drillType' <> 'rollback' then raise exception 'wrong_drill_type'; end if;
  end if;

  if p_supersedes_receipt_id is not null and not exists(
    select 1 from public.tw_release_certification_receipts
    where id=p_supersedes_receipt_id and run_id=p_run_id and requirement_key=p_requirement_key
  ) then raise exception 'superseded_receipt_mismatch'; end if;

  insert into public.tw_release_certification_receipts(
    run_id,requirement_key,outcome,evidence_ref,safe_summary,drill_id,metadata,staff_user_id,supersedes_receipt_id
  ) values (
    p_run_id,p_requirement_key,p_outcome,left(trim(p_evidence_ref),500),
    left(nullif(trim(coalesce(p_safe_summary,'')),''),1000),p_drill_id,p_metadata,p_staff_user_id,p_supersedes_receipt_id
  ) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.tw_release_derived_evidence_pass(p_evidence_key text)
returns boolean
language plpgsql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
declare
  v_status jsonb;
  v_active_sha text;
begin
  v_active_sha:=public.tw_release_active_candidate()->>'releaseCandidateSha';

  if p_evidence_key in ('sandbox_certification_passed','rollback_drill_passed','synthetic_incident_drill_passed')
     and v_active_sha is null then
    return false;
  end if;

  if p_evidence_key='sandbox_certification_passed' then
    return exists(
      select 1 from public.tw_release_certification_runs r
      where r.release_candidate_sha=v_active_sha
        and coalesce((public.tw_release_certification_status(r.id)->>'passed')::boolean,false)=true
    );
  elsif p_evidence_key='rollback_drill_passed' then
    return exists(
      select 1 from public.tw_release_drill_runs d
      where d.release_candidate_sha=v_active_sha
        and d.drill_type='rollback'
        and coalesce((public.tw_release_drill_status(d.id)->>'passed')::boolean,false)=true
    );
  elsif p_evidence_key='synthetic_incident_drill_passed' then
    return exists(
      select 1 from public.tw_release_drill_runs d
      where d.release_candidate_sha=v_active_sha
        and d.drill_type='synthetic_incident'
        and coalesce((public.tw_release_drill_status(d.id)->>'passed')::boolean,false)=true
    );
  elsif p_evidence_key='staff_coverage_current' then
    return
      exists(select 1 from auth.users where coalesce(raw_app_meta_data->>'thisweek_role','')='admin')
      and exists(select 1 from auth.users where coalesce(raw_app_meta_data->>'thisweek_role','') in ('risk_ops','admin'))
      and exists(select 1 from auth.users where coalesce(raw_app_meta_data->>'thisweek_role','') in ('support_ops','admin'));
  elsif p_evidence_key='notification_channel_healthy' then
    return exists(
      select 1 from public.tw_ops_notification_channel_status
      where channel_key='external_webhook' and configured=true and state='healthy'
    );
  elsif p_evidence_key='production_risk_policy_active' then
    return exists(select 1 from public.tw_risk_policies where environment='production' and active=true);
  elsif p_evidence_key in ('production_legal_set_active','production_retention_policy_active','sensitive_access_audit_active') then
    v_status:=public.tw_release_status();
    if p_evidence_key='production_legal_set_active' then
      return coalesce((v_status->>'productionLegalSetActive')::boolean,false);
    elsif p_evidence_key='production_retention_policy_active' then
      return coalesce((v_status->>'productionRetentionPolicyActive')::boolean,false);
    else
      return coalesce((v_status->>'sensitiveAccessAuditActive')::boolean,false);
    end if;
  end if;
  return false;
end;
$$;

create or replace function public.tw_release_candidate_report(p_release_candidate_sha text default null)
returns jsonb
language plpgsql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
declare
  v_sha text;
  v_active jsonb;
begin
  v_active:=public.tw_release_active_candidate();
  v_sha:=coalesce(lower(trim(p_release_candidate_sha)),v_active->>'releaseCandidateSha');

  if v_sha is null then
    return jsonb_build_object(
      'exists',false,
      'releaseCandidateSha',null,
      'isActive',false,
      'latestCertification',null,
      'drills','[]'::jsonb
    );
  end if;

  return jsonb_build_object(
    'exists',exists(select 1 from public.tw_release_candidate_selections where release_candidate_sha=v_sha),
    'releaseCandidateSha',v_sha,
    'isActive',v_sha=(v_active->>'releaseCandidateSha'),
    'selection',(
      select jsonb_build_object(
        'selectionId',s.id,'sourceRef',s.source_ref,'note',s.note,
        'selectedBy',s.staff_user_id,'selectedAt',s.created_at
      )
      from public.tw_release_candidate_selections s
      where s.release_candidate_sha=v_sha
      order by s.created_at desc,s.id desc limit 1
    ),
    'latestCertification',(
      select public.tw_release_certification_status(r.id)
      from public.tw_release_certification_runs r
      where r.release_candidate_sha=v_sha
      order by r.started_at desc limit 1
    ),
    'drills',coalesce((
      select jsonb_agg(public.tw_release_drill_status(d.id) order by d.started_at desc)
      from public.tw_release_drill_runs d
      where d.release_candidate_sha=v_sha
    ),'[]'::jsonb)
  );
end;
$$;

create or replace function public.tw_release_readiness_report()
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  with active as (
    select public.tw_release_active_candidate() as candidate
  ),
  gates as (
    select
      g.gate_key,g.category,g.label,g.required_for_live_money,g.verified,g.verified_at,g.evidence_ref,
      public.tw_release_gate_evidence_status(g.gate_key) as evidence
    from public.tw_release_gates g
    order by g.category,g.gate_key
  )
  select jsonb_build_object(
    'generatedAt',now(),
    'activeCandidate',(select candidate from active),
    'candidateReport',public.tw_release_candidate_report(null),
    'releaseStatus',public.tw_release_status(),
    'gates',coalesce((select jsonb_agg(jsonb_build_object(
      'gateKey',gate_key,'category',category,'label',label,'required',required_for_live_money,
      'verified',verified,'verifiedAt',verified_at,'evidenceRef',evidence_ref,'evidence',evidence
    )) from gates),'[]'::jsonb),
    'blockingGateKeys',coalesce((select jsonb_agg(gate_key) from gates
      where required_for_live_money and (verified=false or coalesce((evidence->>'ready')::boolean,false)=false)
    ),'[]'::jsonb)
  );
$$;

revoke all on function public.tw_release_active_candidate() from public,anon,authenticated;
revoke all on function public.tw_release_select_candidate(uuid,text,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_candidate_report(text) from public,anon,authenticated;
revoke all on function public.tw_release_start_certification(uuid,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_start_drill(uuid,text,text,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_finish_drill(uuid,uuid,boolean,text,text) from public,anon,authenticated;
revoke all on function public.tw_release_record_certification_receipt(uuid,uuid,text,text,text,text,uuid,jsonb,bigint) from public,anon,authenticated;
revoke all on function public.tw_release_derived_evidence_pass(text) from public,anon,authenticated;
revoke all on function public.tw_release_readiness_report() from public,anon,authenticated;

grant execute on function public.tw_release_active_candidate() to service_role;
grant execute on function public.tw_release_select_candidate(uuid,text,text,text) to service_role;
grant execute on function public.tw_release_candidate_report(text) to service_role;
grant execute on function public.tw_release_start_certification(uuid,text,text) to service_role;
grant execute on function public.tw_release_start_drill(uuid,text,text,text,text) to service_role;
grant execute on function public.tw_release_finish_drill(uuid,uuid,boolean,text,text) to service_role;
grant execute on function public.tw_release_record_certification_receipt(uuid,uuid,text,text,text,text,uuid,jsonb,bigint) to service_role;
grant execute on function public.tw_release_derived_evidence_pass(text) to service_role;
grant execute on function public.tw_release_readiness_report() to service_role;

commit;
