-- Phase 20 — Money Layer Foundation
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Core rules:
--   1. Browser-local Plan is not custody/accounting authority.
--   2. Money history is append-only; corrections use compensating journals.
--   3. Integer cents + USD.
--   4. Direct browser access is revoked; service gateway only.
--   5. No PAN/CVV/full bank credentials/provider secrets are stored in these tables.

begin;

create schema if not exists tw_internal;
revoke all on schema tw_internal from public, anon, authenticated;

create table if not exists public.tw_money_customers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  banking_provider text,
  provider_customer_id text,
  onboarding_state text not null default 'not_started'
    check (onboarding_state in ('not_started','identity_required','submitted','approved','restricted','rejected','closed')),
  kyc_state text not null default 'not_started'
    check (kyc_state in ('not_started','pending','verified','manual_review','failed','expired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_money_deposit_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  money_customer_id uuid not null references public.tw_money_customers(id) on delete cascade,
  provider text not null,
  provider_account_id text not null,
  account_kind text not null default 'checking' check (account_kind in ('checking','savings','wallet')),
  status text not null default 'pending' check (status in ('pending','open','frozen','restricted','closed')),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  routing_last4 text check (routing_last4 is null or routing_last4 ~ '^[0-9]{4}$'),
  account_last4 text check (account_last4 is null or account_last4 ~ '^[0-9]{4}$'),
  capabilities jsonb not null default '{}'::jsonb,
  opened_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, provider, provider_account_id)
);

create table if not exists public.tw_money_envelopes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  envelope_key text not null,
  label text not null,
  envelope_type text not null check (envelope_type in ('bills','essentials','lifestyle','savings','custom')),
  linked_plan_ref text,
  status text not null default 'active' check (status in ('active','paused','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, envelope_key)
);

create table if not exists public.tw_money_ledger_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  deposit_account_id uuid references public.tw_money_deposit_accounts(id) on delete restrict,
  envelope_id uuid references public.tw_money_envelopes(id) on delete restrict,
  account_code text not null,
  account_kind text not null check (account_kind in (
    'cash_asset','envelope_available','card_hold','bill_hold',
    'transfer_clearing','reward_expense','reward_payable','fee_expense','external_offset'
  )),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  status text not null default 'active' check (status in ('active','frozen','closed')),
  created_at timestamptz not null default now(),
  unique(user_id, account_code)
);

create table if not exists public.tw_money_journals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  event_type text not null,
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  idempotency_key text not null,
  provider text,
  provider_event_id text,
  effective_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id, idempotency_key)
);

create table if not exists public.tw_money_ledger_entries (
  id bigint generated by default as identity primary key,
  journal_id uuid not null references public.tw_money_journals(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete restrict,
  ledger_account_id uuid not null references public.tw_money_ledger_accounts(id) on delete restrict,
  amount_cents bigint not null check (amount_cents <> 0),
  created_at timestamptz not null default now()
);

create index if not exists tw_money_entries_user_account_idx
  on public.tw_money_ledger_entries(user_id, ledger_account_id, id);
create index if not exists tw_money_journals_provider_idx
  on public.tw_money_journals(provider, provider_event_id) where provider_event_id is not null;

create table if not exists public.tw_money_authorizations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  authorization_kind text not null check (authorization_kind in ('ach_debit','ach_credit','bill_payment','card_issue','direct_deposit_switch')),
  terms_version text not null,
  consent_text_hash text not null,
  provider text,
  provider_authorization_id text,
  accepted_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.tw_money_funding_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_connection_id uuid references public.tw_provider_connections(id) on delete set null,
  provider_account_row_id uuid references public.tw_provider_accounts(id) on delete set null,
  verification_provider text not null default 'plaid',
  processor_provider text,
  processor_reference text,
  account_kind text check (account_kind in ('checking','savings')),
  account_last4 text check (account_last4 is null or account_last4 ~ '^[0-9]{4}$'),
  routing_last4 text check (routing_last4 is null or routing_last4 ~ '^[0-9]{4}$'),
  status text not null default 'pending' check (status in ('pending','verified','restricted','disconnected')),
  supported_rails jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_money_transfers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  transfer_type text not null check (transfer_type in ('funding_in','cash_out','internal','reward','bill_pay','refund','reversal')),
  rail text not null check (rail in ('ach','rtp','book','provider_transfer','method','card')),
  source_kind text not null,
  source_ref uuid,
  destination_kind text not null,
  destination_ref uuid,
  amount_cents bigint not null check (amount_cents > 0),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  state text not null default 'draft'
    check (state in ('draft','authorization_required','authorized','submitted','pending','settled','failed','returned','cancelled','reversed')),
  authorization_id uuid references public.tw_money_authorizations(id) on delete restrict,
  provider text,
  provider_transfer_id text,
  idempotency_key text not null,
  failure_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  settled_at timestamptz,
  unique(user_id, idempotency_key)
);

create table if not exists public.tw_money_transfer_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  transfer_id uuid not null references public.tw_money_transfers(id) on delete cascade,
  state text not null,
  provider_event_id text,
  detail_code text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists tw_money_transfer_events_transfer_idx
  on public.tw_money_transfer_events(transfer_id, id);

create table if not exists public.tw_money_direct_deposit_switches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  target_deposit_account_id uuid not null references public.tw_money_deposit_accounts(id) on delete restrict,
  provider text not null default 'pinwheel',
  provider_link_id text,
  provider_job_id text,
  allocation_kind text not null default 'full' check (allocation_kind in ('full','percent','amount')),
  allocation_value bigint,
  state text not null default 'draft'
    check (state in ('draft','link_created','in_progress','submitted','confirmed','failed','cancelled')),
  failure_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create table if not exists public.tw_money_payroll_deposits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  deposit_account_id uuid not null references public.tw_money_deposit_accounts(id) on delete restrict,
  provider text not null,
  provider_transaction_id text not null,
  employer_label text,
  amount_cents bigint not null check (amount_cents > 0),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  posted_at timestamptz not null,
  qualifying_direct_deposit boolean not null default false,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique(provider, provider_transaction_id)
);

create table if not exists public.tw_money_reward_offers (
  id uuid primary key default gen_random_uuid(),
  offer_code text not null unique,
  title text not null,
  reward_amount_cents bigint not null check (reward_amount_cents > 0),
  minimum_qualifying_deposit_cents bigint not null default 0 check (minimum_qualifying_deposit_cents >= 0),
  qualification_window_days integer not null default 45 check (qualification_window_days between 1 and 365),
  terms_version text not null,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_money_reward_enrollments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  offer_id uuid not null references public.tw_money_reward_offers(id) on delete restrict,
  direct_deposit_switch_id uuid references public.tw_money_direct_deposit_switches(id) on delete set null,
  status text not null default 'enrolled'
    check (status in ('enrolled','awaiting_deposit','qualified','disqualified','payout_pending','paid','expired','cancelled')),
  enrolled_at timestamptz not null default now(),
  qualifying_deposit_id uuid references public.tw_money_payroll_deposits(id) on delete set null,
  payout_transfer_id uuid references public.tw_money_transfers(id) on delete set null,
  paid_at timestamptz,
  disqualification_code text,
  unique(user_id, offer_id)
);

create table if not exists public.tw_money_billers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  discovery_provider text,
  provider_biller_id text,
  display_name text not null,
  bill_type text,
  account_mask text,
  status text not null default 'active' check (status in ('active','paused','closed')),
  autopay_state text not null default 'unknown'
    check (autopay_state in ('unknown','off','on_external','on_thisweek','switch_pending','switch_failed')),
  due_day integer check (due_day between 1 and 31),
  safe_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_money_virtual_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  deposit_account_id uuid references public.tw_money_deposit_accounts(id) on delete restrict,
  envelope_id uuid references public.tw_money_envelopes(id) on delete restrict,
  biller_id uuid references public.tw_money_billers(id) on delete set null,
  provider text not null,
  provider_card_id text,
  card_mode text not null check (card_mode in ('category','bill','single_use','merchant_locked')),
  label text not null,
  status text not null default 'pending' check (status in ('pending','active','paused','spent','closed')),
  spend_limit_cents bigint check (spend_limit_cents is null or spend_limit_cents > 0),
  allowed_mcc text[] not null default '{}',
  merchant_lock_fingerprint text,
  last4 text check (last4 is null or last4 ~ '^[0-9]{4}$'),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_money_card_authorizations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  card_id uuid not null references public.tw_money_virtual_cards(id) on delete cascade,
  provider text not null,
  provider_authorization_id text not null,
  amount_cents bigint not null check (amount_cents > 0),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  merchant_name text,
  merchant_id text,
  mcc text,
  decision text not null check (decision in ('approved','declined','pending')),
  decision_reason text,
  state text not null default 'authorized' check (state in ('authorized','reversed','settled','expired')),
  hold_journal_id uuid references public.tw_money_journals(id) on delete restrict,
  settlement_journal_id uuid references public.tw_money_journals(id) on delete restrict,
  requested_at timestamptz not null default now(),
  settled_at timestamptz,
  final_amount_cents bigint check (final_amount_cents is null or final_amount_cents >= 0),
  unique(provider, provider_authorization_id)
);

create table if not exists public.tw_money_bill_payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  biller_id uuid not null references public.tw_money_billers(id) on delete restrict,
  source_deposit_account_id uuid references public.tw_money_deposit_accounts(id) on delete restrict,
  source_funding_account_id uuid references public.tw_money_funding_accounts(id) on delete restrict,
  source_envelope_id uuid references public.tw_money_envelopes(id) on delete restrict,
  virtual_card_id uuid references public.tw_money_virtual_cards(id) on delete set null,
  authorization_id uuid references public.tw_money_authorizations(id) on delete restrict,
  amount_cents bigint not null check (amount_cents > 0),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  payment_rail text not null check (payment_rail in ('method','ach','virtual_card')),
  provider text not null,
  provider_payment_id text,
  state text not null default 'draft'
    check (state in ('draft','authorization_required','authorized','scheduled','submitted','processing','paid','failed','returned','cancelled','reversed')),
  scheduled_for timestamptz,
  idempotency_key text not null,
  failure_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  unique(user_id, idempotency_key)
);

create index if not exists tw_money_bill_payments_source_funding_idx
  on public.tw_money_bill_payments(user_id, source_funding_account_id)
  where source_funding_account_id is not null;

create table if not exists public.tw_money_bill_switches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  biller_id uuid references public.tw_money_billers(id) on delete set null,
  provider text not null default 'pinwheel',
  provider_job_id text,
  target_kind text not null check (target_kind in ('deposit_account','virtual_card')),
  target_ref uuid not null,
  state text not null default 'draft'
    check (state in ('draft','link_created','in_progress','submitted','confirmed','failed','cancelled')),
  failure_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create table if not exists public.tw_money_provider_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  user_id uuid references auth.users(id) on delete set null,
  payload_hash text not null,
  safe_summary jsonb not null default '{}'::jsonb,
  state text not null default 'received' check (state in ('received','processing','processed','ignored','failed')),
  error_code text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique(provider, provider_event_id)
);

create or replace function tw_internal.reject_money_history_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'This Week money ledger history is append-only; post a compensating journal instead.';
end;
$$;

drop trigger if exists tw_money_journals_immutable on public.tw_money_journals;
create trigger tw_money_journals_immutable
before update or delete on public.tw_money_journals
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_money_entries_immutable on public.tw_money_ledger_entries;
create trigger tw_money_entries_immutable
before update or delete on public.tw_money_ledger_entries
for each row execute function tw_internal.reject_money_history_mutation();

create or replace function public.tw_money_post_journal(
  p_user_id uuid,
  p_event_type text,
  p_idempotency_key text,
  p_currency text,
  p_entries jsonb,
  p_provider text default null,
  p_provider_event_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_existing uuid;
  v_journal uuid;
  v_count integer;
  v_sum bigint := 0;
  v_entry jsonb;
  v_account uuid;
  v_amount bigint;
begin
  if p_user_id is null then raise exception 'user_id_required'; end if;
  if coalesce(length(trim(p_event_type)),0) < 2 then raise exception 'event_type_required'; end if;
  if coalesce(length(trim(p_idempotency_key)),0) < 8 then raise exception 'idempotency_key_too_short'; end if;
  if p_currency is null or p_currency !~ '^[A-Z]{3}$' then raise exception 'invalid_currency'; end if;
  if jsonb_typeof(p_entries) <> 'array' then raise exception 'entries_must_be_array'; end if;

  select id into v_existing from public.tw_money_journals
  where user_id=p_user_id and idempotency_key=p_idempotency_key;
  if v_existing is not null then return v_existing; end if;

  v_count := jsonb_array_length(p_entries);
  if v_count < 2 or v_count > 32 then raise exception 'invalid_entry_count'; end if;

  for v_entry in select value from jsonb_array_elements(p_entries)
  loop
    v_account := (v_entry->>'ledger_account_id')::uuid;
    v_amount := (v_entry->>'amount_cents')::bigint;
    if v_amount = 0 then raise exception 'zero_entry_not_allowed'; end if;
    if not exists (
      select 1 from public.tw_money_ledger_accounts
      where id=v_account and user_id=p_user_id and currency=p_currency and status='active'
    ) then raise exception 'ledger_account_not_available'; end if;
    v_sum := v_sum + v_amount;
  end loop;

  if v_sum <> 0 then raise exception 'journal_not_balanced'; end if;

  insert into public.tw_money_journals(
    user_id,event_type,currency,idempotency_key,provider,provider_event_id,metadata
  ) values (
    p_user_id,trim(p_event_type),p_currency,trim(p_idempotency_key),
    nullif(trim(coalesce(p_provider,'')),''),
    nullif(trim(coalesce(p_provider_event_id,'')),''),
    coalesce(p_metadata,'{}'::jsonb)
  ) returning id into v_journal;

  for v_entry in select value from jsonb_array_elements(p_entries)
  loop
    insert into public.tw_money_ledger_entries(journal_id,user_id,ledger_account_id,amount_cents)
    values (v_journal,p_user_id,(v_entry->>'ledger_account_id')::uuid,(v_entry->>'amount_cents')::bigint);
  end loop;

  return v_journal;
end;
$$;

create or replace function public.tw_money_move_balance(
  p_user_id uuid,
  p_source_account_id uuid,
  p_destination_account_id uuid,
  p_amount_cents bigint,
  p_event_type text,
  p_idempotency_key text,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_source_balance bigint;
  v_source_currency text;
  v_destination_currency text;
begin
  if p_amount_cents is null or p_amount_cents <= 0 then raise exception 'amount_must_be_positive'; end if;
  if p_source_account_id = p_destination_account_id then raise exception 'source_equals_destination'; end if;

  perform 1 from public.tw_money_ledger_accounts
  where id in (p_source_account_id,p_destination_account_id)
    and user_id=p_user_id and status='active'
  order by id for update;

  if (
    select count(*) from public.tw_money_ledger_accounts
    where id in (p_source_account_id,p_destination_account_id)
      and user_id=p_user_id and status='active'
  ) <> 2 then raise exception 'ledger_account_not_available'; end if;

  select currency into v_source_currency from public.tw_money_ledger_accounts
  where id=p_source_account_id and user_id=p_user_id;
  select currency into v_destination_currency from public.tw_money_ledger_accounts
  where id=p_destination_account_id and user_id=p_user_id;
  if v_source_currency <> v_destination_currency then raise exception 'currency_mismatch'; end if;

  select coalesce(sum(amount_cents),0) into v_source_balance
  from public.tw_money_ledger_entries
  where user_id=p_user_id and ledger_account_id=p_source_account_id;
  if v_source_balance < p_amount_cents then raise exception 'insufficient_ledger_balance'; end if;

  return public.tw_money_post_journal(
    p_user_id,p_event_type,p_idempotency_key,v_source_currency,
    jsonb_build_array(
      jsonb_build_object('ledger_account_id',p_source_account_id,'amount_cents',-p_amount_cents),
      jsonb_build_object('ledger_account_id',p_destination_account_id,'amount_cents',p_amount_cents)
    ),
    null,null,coalesce(p_metadata,'{}'::jsonb)
  );
end;
$$;

revoke all on function public.tw_money_post_journal(uuid,text,text,text,jsonb,text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.tw_money_post_journal(uuid,text,text,text,jsonb,text,text,jsonb)
  to service_role;

revoke all on function public.tw_money_move_balance(uuid,uuid,uuid,bigint,text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.tw_money_move_balance(uuid,uuid,uuid,bigint,text,text,jsonb)
  to service_role;

insert into public.tw_money_reward_offers(
  offer_code,title,reward_amount_cents,minimum_qualifying_deposit_cents,
  qualification_window_days,terms_version,active
) values (
  'TW_DD_SWITCH_25_SANDBOX',
  'Sandbox direct-deposit switch reward',
  2500,50000,45,'sandbox-2026-09',false
)
on conflict (offer_code) do update set
  reward_amount_cents=excluded.reward_amount_cents,
  minimum_qualifying_deposit_cents=excluded.minimum_qualifying_deposit_cents,
  qualification_window_days=excluded.qualification_window_days,
  terms_version=excluded.terms_version,
  active=false,
  updated_at=now();

do $$
declare t text;
begin
  foreach t in array array[
    'tw_money_customers','tw_money_deposit_accounts','tw_money_envelopes',
    'tw_money_ledger_accounts','tw_money_journals','tw_money_ledger_entries',
    'tw_money_authorizations','tw_money_funding_accounts','tw_money_transfers',
    'tw_money_transfer_events','tw_money_direct_deposit_switches','tw_money_payroll_deposits',
    'tw_money_reward_offers','tw_money_reward_enrollments','tw_money_billers',
    'tw_money_virtual_cards','tw_money_card_authorizations','tw_money_bill_payments',
    'tw_money_bill_switches','tw_money_provider_events'
  ]
  loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on table public.%I from public, anon, authenticated',t);
    execute format('grant select,insert,update,delete on table public.%I to service_role',t);
  end loop;
end $$;

revoke all on all sequences in schema public from public, anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

comment on table public.tw_money_journals is
  'Append-only This Week money journal. Corrections use compensating journals; never rewrite posted history.';
comment on table public.tw_money_ledger_entries is
  'Signed integer-cent double-entry postings. Every journal must sum to zero.';
comment on table public.tw_money_envelopes is
  'Server money allocation controls. These do not redefine the browser-local weekly Plan.';
comment on table public.tw_money_virtual_cards is
  'Provider card references and policy metadata only. Never store PAN, CVV, full account number, or provider secret here.';
comment on table public.tw_money_reward_offers is
  'Rewards are disabled unless explicitly activated after terms, funding, abuse controls, and provider review.';

commit;
