-- Phase 25 — Risk & Velocity Controls
-- Canonical source record for the deployed Phase 25 risk layer; database objects were applied on 2026-09-19.
-- Application-level controls are subordinate to provider/program/bank controls.

begin;

create table if not exists public.tw_risk_policies (
  id uuid primary key default gen_random_uuid(),
  environment text not null check (environment in ('sandbox','production')),
  policy_version text not null,
  active boolean not null default false,
  rules jsonb not null,
  created_at timestamptz not null default now(),
  unique(environment, policy_version)
);

create unique index if not exists tw_risk_one_active_policy_per_env
  on public.tw_risk_policies(environment) where active;

create table if not exists public.tw_risk_user_controls (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state text not null default 'normal'
    check (state in ('normal','restricted','frozen','closed')),
  reason_code text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_risk_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  environment text not null check (environment in ('sandbox','production')),
  action text not null,
  amount_cents bigint not null default 0 check (amount_cents >= 0),
  idempotency_key text not null,
  decision text not null check (decision in ('allow','review','deny')),
  reason_code text not null,
  policy_id uuid references public.tw_risk_policies(id) on delete restrict,
  resource_ref text,
  safe_context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id, action, idempotency_key)
);

create index if not exists tw_risk_events_velocity_idx
  on public.tw_risk_events(user_id, environment, action, created_at desc);

create table if not exists public.tw_risk_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  risk_event_id bigint not null unique references public.tw_risk_events(id) on delete cascade,
  state text not null default 'pending'
    check (state in ('pending','approved','denied','cancelled')),
  resolution_code text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

do $$
declare t text;
begin
  foreach t in array array['tw_risk_policies','tw_risk_user_controls','tw_risk_events','tw_risk_reviews']
  loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on table public.%I from public, anon, authenticated',t);
    execute format('grant select,insert,update,delete on table public.%I to service_role',t);
  end loop;
end $$;

insert into public.tw_risk_policies(environment,policy_version,active,rules)
values (
  'sandbox','2026-09-sandbox-v1',true,
  '{
    "external_ach_pull":{"per_txn_hard_cents":100000,"daily_hard_cents":200000,"daily_count_hard":5,"review_over_cents":50000},
    "bill_payment":{"per_txn_hard_cents":50000,"daily_hard_cents":100000,"daily_count_hard":10,"review_over_cents":25000},
    "virtual_card_issue":{"per_txn_hard_cents":250000,"daily_count_hard":5,"review_over_cents":100000},
    "card_authorization":{"per_txn_hard_cents":50000,"daily_hard_cents":150000,"daily_count_hard":50},
    "direct_deposit_switch":{"daily_count_hard":3},
    "provider_link":{"daily_count_hard":5}
  }'::jsonb
)
on conflict (environment,policy_version) do update
set active=true,rules=excluded.rules;

insert into public.tw_risk_policies(environment,policy_version,active,rules)
values (
  'production','2026-09-production-template-v1',false,
  '{
    "external_ach_pull":{"status":"approval_required"},
    "bill_payment":{"status":"approval_required"},
    "virtual_card_issue":{"status":"approval_required"},
    "card_authorization":{"status":"approval_required"},
    "direct_deposit_switch":{"status":"approval_required"},
    "provider_link":{"status":"approval_required"}
  }'::jsonb
)
on conflict (environment,policy_version) do update
set active=false,rules=excluded.rules;

create or replace function public.tw_risk_evaluate_action(
  p_user_id uuid,
  p_environment text,
  p_action text,
  p_amount_cents bigint,
  p_idempotency_key text,
  p_resource_ref text default null,
  p_safe_context jsonb default '{}'::jsonb
)
returns table(risk_event_id bigint,decision text,reason_code text,policy_version text)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_existing public.tw_risk_events%rowtype;
  v_control_state text := 'normal';
  v_policy public.tw_risk_policies%rowtype;
  v_rule jsonb;
  v_daily_count bigint := 0;
  v_daily_amount bigint := 0;
  v_per_txn bigint;
  v_daily_hard bigint;
  v_count_hard bigint;
  v_review_over bigint;
  v_decision text := 'allow';
  v_reason text := 'within_policy';
  v_event_id bigint;
begin
  if p_user_id is null then raise exception 'user_id_required'; end if;
  if p_environment not in ('sandbox','production') then raise exception 'invalid_risk_environment'; end if;
  if coalesce(length(trim(p_action)),0)<2 then raise exception 'risk_action_required'; end if;
  if coalesce(length(trim(p_idempotency_key)),0)<8 then raise exception 'risk_idempotency_key_required'; end if;
  if p_amount_cents is null or p_amount_cents<0 then raise exception 'invalid_risk_amount'; end if;

  perform pg_advisory_xact_lock(hashtextextended('tw-risk:'||p_user_id::text,0));

  select * into v_existing from public.tw_risk_events
  where user_id=p_user_id and action=p_action and idempotency_key=p_idempotency_key limit 1;
  if v_existing.id is not null then
    return query select v_existing.id,v_existing.decision,v_existing.reason_code,
      coalesce((select rp.policy_version from public.tw_risk_policies rp where rp.id=v_existing.policy_id),'unknown');
    return;
  end if;

  select coalesce((select c.state from public.tw_risk_user_controls c
    where c.user_id=p_user_id and (c.expires_at is null or c.expires_at>now())),'normal')
  into v_control_state;

  select * into v_policy from public.tw_risk_policies
  where environment=p_environment and active=true order by created_at desc limit 1;

  if v_control_state in ('restricted','frozen','closed') then
    v_decision:='deny'; v_reason:='user_'||v_control_state;
  elsif v_policy.id is null then
    v_decision:='deny'; v_reason:='risk_policy_unavailable';
  else
    v_rule:=v_policy.rules->p_action;
    if v_rule is null then
      v_decision:='deny'; v_reason:='action_not_allowed';
    else
      v_per_txn:=nullif(v_rule->>'per_txn_hard_cents','')::bigint;
      v_daily_hard:=nullif(v_rule->>'daily_hard_cents','')::bigint;
      v_count_hard:=nullif(v_rule->>'daily_count_hard','')::bigint;
      v_review_over:=nullif(v_rule->>'review_over_cents','')::bigint;

      select count(*),coalesce(sum(amount_cents),0)
      into v_daily_count,v_daily_amount
      from public.tw_risk_events
      where user_id=p_user_id and environment=p_environment and action=p_action
        and decision in ('allow','review') and created_at>=date_trunc('day',now());

      if v_per_txn is not null and p_amount_cents>v_per_txn then
        v_decision:='deny'; v_reason:='per_transaction_limit';
      elsif v_count_hard is not null and v_daily_count>=v_count_hard then
        v_decision:='deny'; v_reason:='daily_count_limit';
      elsif v_daily_hard is not null and v_daily_amount+p_amount_cents>v_daily_hard then
        v_decision:='deny'; v_reason:='daily_amount_limit';
      elsif v_review_over is not null and p_amount_cents>=v_review_over then
        v_decision:='review'; v_reason:='manual_review_threshold';
      end if;
    end if;
  end if;

  insert into public.tw_risk_events(
    user_id,environment,action,amount_cents,idempotency_key,
    decision,reason_code,policy_id,resource_ref,safe_context
  ) values (
    p_user_id,p_environment,trim(p_action),p_amount_cents,trim(p_idempotency_key),
    v_decision,v_reason,v_policy.id,nullif(trim(coalesce(p_resource_ref,'')),''),
    coalesce(p_safe_context,'{}'::jsonb)
  ) returning id into v_event_id;

  if v_decision='review' then
    insert into public.tw_risk_reviews(user_id,risk_event_id)
    values(p_user_id,v_event_id) on conflict (risk_event_id) do nothing;
  end if;

  risk_event_id:=v_event_id;decision:=v_decision;reason_code:=v_reason;
  policy_version:=coalesce(v_policy.policy_version,'none');return next;
end;
$$;

revoke all on function public.tw_risk_evaluate_action(uuid,text,text,bigint,text,text,jsonb)
  from public,anon,authenticated;
grant execute on function public.tw_risk_evaluate_action(uuid,text,text,bigint,text,text,jsonb)
  to service_role;

-- The deployed schema also includes service-role-only
-- tw_money_risk_reserve_card_authorization(...), which evaluates
-- card_authorization risk and posts the envelope hold only after allow.

commit;
