-- Phase 26 — Returns, Negative Balances & Dispute Operations
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Canonical source record for the server-only operational lifecycle layer.

begin;

create table if not exists public.tw_ops_cases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  case_key text not null unique,
  case_type text not null check (case_type in (
    'ach_return','payment_return','negative_balance','card_dispute','card_refund','provider_failure'
  )),
  provider text,
  provider_case_id text,
  resource_ref text,
  related_transfer_id uuid references public.tw_money_transfers(id) on delete set null,
  related_card_authorization_id uuid references public.tw_money_card_authorizations(id) on delete set null,
  amount_cents bigint check (amount_cents is null or amount_cents >= 0),
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')),
  state text not null default 'open' check (state in ('open','monitoring','action_required','resolved','closed')),
  reason_code text,
  safe_detail jsonb not null default '{}'::jsonb,
  opened_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.tw_ops_case_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.tw_ops_cases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  event_type text not null,
  state text,
  reason_code text,
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(case_id,event_key)
);

create index if not exists tw_ops_cases_user_state_idx
  on public.tw_ops_cases(user_id,state,updated_at desc);
create index if not exists tw_ops_case_events_case_idx
  on public.tw_ops_case_events(case_id,id);

alter table public.tw_ops_cases enable row level security;
alter table public.tw_ops_case_events enable row level security;
revoke all on table public.tw_ops_cases, public.tw_ops_case_events from public,anon,authenticated;
grant select,insert,update,delete on table public.tw_ops_cases, public.tw_ops_case_events to service_role;

-- Deployed service-role RPCs:
-- tw_ops_open_case(...)
--   Idempotently opens/updates an operational case and appends a case event.
-- tw_ops_reconcile_cash_control(uuid)
--   Clears only the negative_cash_balance restriction when the cloud cash ledger recovers.
-- tw_money_apply_unit_ach_return(uuid,text,text,bigint,text)
--   Reverses a previously posted Unit ACH cash credit exactly once; if the cash ledger turns
--   negative it opens a critical case and applies a negative-balance restriction without
--   downgrading frozen/closed or unrelated restricted controls.
-- tw_money_apply_unit_card_credit(uuid,text,text,bigint,text,text,text)
--   Posts a provider card credit back to the card's bound envelope and opens/updates its case.
-- tw_ops_record_unit_dispute(uuid,text,text,text,bigint,text,text)
--   Tracks InvestigationStarted / ProvisionallyCredited / Denied / ResolvedLost / ResolvedWon.

revoke all on function public.tw_ops_open_case(uuid,text,text,text,text,text,uuid,uuid,bigint,text,text,text,jsonb,text,text)
  from public,anon,authenticated;
grant execute on function public.tw_ops_open_case(uuid,text,text,text,text,text,uuid,uuid,bigint,text,text,text,jsonb,text,text)
  to service_role;

revoke all on function public.tw_ops_reconcile_cash_control(uuid) from public,anon,authenticated;
grant execute on function public.tw_ops_reconcile_cash_control(uuid) to service_role;

revoke all on function public.tw_money_apply_unit_ach_return(uuid,text,text,bigint,text)
  from public,anon,authenticated;
grant execute on function public.tw_money_apply_unit_ach_return(uuid,text,text,bigint,text)
  to service_role;

revoke all on function public.tw_money_apply_unit_card_credit(uuid,text,text,bigint,text,text,text)
  from public,anon,authenticated;
grant execute on function public.tw_money_apply_unit_card_credit(uuid,text,text,bigint,text,text,text)
  to service_role;

revoke all on function public.tw_ops_record_unit_dispute(uuid,text,text,text,bigint,text,text)
  from public,anon,authenticated;
grant execute on function public.tw_ops_record_unit_dispute(uuid,text,text,text,bigint,text,text)
  to service_role;

drop trigger if exists tw_ops_case_events_immutable on public.tw_ops_case_events;
create trigger tw_ops_case_events_immutable
before update or delete on public.tw_ops_case_events
for each row execute function tw_internal.reject_money_history_mutation();

comment on table public.tw_ops_cases is
  'Server-only operational lifecycle cases for returns, negative balances, disputes, refunds and provider failures.';
comment on table public.tw_ops_case_events is
  'Append-only operational case event history. Corrections append a new event rather than rewriting prior events.';

commit;
