-- Phase 27 — Staff Operations, Manual Review & RBAC
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Browser roles cannot access these tables/RPCs directly.

begin;

alter table public.tw_ops_cases
  add column if not exists assigned_to_staff_user_id uuid references auth.users(id) on delete set null,
  add column if not exists assigned_at timestamptz;

alter table public.tw_risk_reviews
  add column if not exists assigned_to_staff_user_id uuid references auth.users(id) on delete set null,
  add column if not exists assigned_at timestamptz,
  add column if not exists resolution_note text;

create table if not exists public.tw_ops_alerts (
  id uuid primary key default gen_random_uuid(),
  alert_key text not null unique,
  user_id uuid references auth.users(id) on delete cascade,
  case_id uuid references public.tw_ops_cases(id) on delete cascade,
  risk_review_id uuid references public.tw_risk_reviews(id) on delete cascade,
  alert_type text not null check (alert_type in ('critical_case','high_case','risk_review','negative_balance','provider_failure')),
  severity text not null check (severity in ('medium','high','critical')),
  state text not null default 'open' check (state in ('open','acknowledged','resolved')),
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  acknowledged_by uuid references auth.users(id) on delete set null,
  acknowledged_at timestamptz,
  resolved_at timestamptz
);

create table if not exists public.tw_ops_staff_actions (
  id bigint generated by default as identity primary key,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  staff_role text not null check (staff_role in ('support_ops','risk_ops','admin')),
  action text not null,
  target_type text not null,
  target_ref text not null,
  reason_code text,
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.tw_ops_alerts enable row level security;
alter table public.tw_ops_staff_actions enable row level security;
revoke all on table public.tw_ops_alerts, public.tw_ops_staff_actions from public,anon,authenticated;
grant select,insert,update,delete on table public.tw_ops_alerts to service_role;
grant select,insert on table public.tw_ops_staff_actions to service_role;

drop trigger if exists tw_ops_staff_actions_immutable on public.tw_ops_staff_actions;
create trigger tw_ops_staff_actions_immutable
before update or delete on public.tw_ops_staff_actions
for each row execute function tw_internal.reject_money_history_mutation();

-- Deployed service-role-only RPCs:
-- tw_ops_record_staff_action(...)
-- tw_ops_resolve_risk_review(...)
-- tw_ops_resolve_case(...)
-- tw_ops_set_user_control(...)
-- tw_ops_assign_case(...)
-- tw_ops_ack_alert(...)
--
-- tw_risk_evaluate_action(...) was upgraded so a prior idempotent event with
-- decision='review' returns allow only after its tw_risk_reviews row is approved.
-- The original risk event is not rewritten.

revoke all on function public.tw_ops_record_staff_action(uuid,text,text,text,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.tw_ops_record_staff_action(uuid,text,text,text,text,text,jsonb) to service_role;

revoke all on function public.tw_ops_resolve_risk_review(uuid,uuid,text,text,text,text) from public,anon,authenticated;
grant execute on function public.tw_ops_resolve_risk_review(uuid,uuid,text,text,text,text) to service_role;

revoke all on function public.tw_ops_resolve_case(uuid,uuid,text,text,text,text) from public,anon,authenticated;
grant execute on function public.tw_ops_resolve_case(uuid,uuid,text,text,text,text) to service_role;

revoke all on function public.tw_ops_set_user_control(uuid,uuid,text,text,text,timestamptz) from public,anon,authenticated;
grant execute on function public.tw_ops_set_user_control(uuid,uuid,text,text,text,timestamptz) to service_role;

revoke all on function public.tw_ops_assign_case(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.tw_ops_assign_case(uuid,uuid,text) to service_role;

revoke all on function public.tw_ops_ack_alert(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.tw_ops_ack_alert(uuid,uuid,text) to service_role;

create index if not exists tw_ops_alerts_state_idx
  on public.tw_ops_alerts(state,severity,updated_at desc);
create index if not exists tw_ops_staff_actions_staff_idx
  on public.tw_ops_staff_actions(staff_user_id,created_at desc);

-- High/critical cases and pending risk reviews are mirrored to tw_ops_alerts by
-- tw_ops_case_alert and tw_risk_review_alert triggers.

commit;
