-- Phase 29 — Automated Health, Reconciliation & Notification Outbox
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Browser roles have no direct access to monitoring/outbox tables.

begin;

alter table public.tw_ops_alerts
  drop constraint if exists tw_ops_alerts_alert_type_check;
alter table public.tw_ops_alerts
  add constraint tw_ops_alerts_alert_type_check
  check (alert_type in (
    'critical_case','high_case','risk_review','negative_balance','provider_failure',
    'health_monitor','reconciliation'
  ));

create table if not exists public.tw_ops_health_snapshots (
  id bigint generated by default as identity primary key,
  health_state text not null check (health_state in ('healthy','degraded','critical')),
  policy_version text not null,
  counts jsonb not null default '{}'::jsonb,
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tw_ops_monitor_runs (
  id bigint generated by default as identity primary key,
  state text not null check (state in ('running','succeeded','failed')),
  snapshot_id bigint references public.tw_ops_health_snapshots(id) on delete set null,
  safe_detail jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.tw_ops_notification_outbox (
  id uuid primary key default gen_random_uuid(),
  notification_key text not null unique,
  channel text not null default 'external_pending'
    check (channel in ('ops_console','external_pending')),
  event_type text not null,
  severity text not null check (severity in ('high','critical')),
  subject text not null check (char_length(subject) between 3 and 160),
  safe_body text not null check (char_length(safe_body) between 1 and 2000),
  alert_id uuid references public.tw_ops_alerts(id) on delete set null,
  incident_id uuid references public.tw_ops_incidents(id) on delete set null,
  state text not null default 'pending'
    check (state in ('pending','sent','failed','suppressed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_attempt_at timestamptz not null default now(),
  last_error_code text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists tw_ops_health_snapshots_created_idx
  on public.tw_ops_health_snapshots(created_at desc);
create index if not exists tw_ops_monitor_runs_started_idx
  on public.tw_ops_monitor_runs(started_at desc);
create index if not exists tw_ops_notification_outbox_state_idx
  on public.tw_ops_notification_outbox(state,next_attempt_at,created_at);

alter table public.tw_ops_health_snapshots enable row level security;
alter table public.tw_ops_monitor_runs enable row level security;
alter table public.tw_ops_notification_outbox enable row level security;

revoke all on table
  public.tw_ops_health_snapshots,
  public.tw_ops_monitor_runs,
  public.tw_ops_notification_outbox
from public,anon,authenticated;

grant select,insert,update,delete on table
  public.tw_ops_health_snapshots,
  public.tw_ops_monitor_runs,
  public.tw_ops_notification_outbox
to service_role;

create or replace function tw_internal.upsert_monitor_alert(
  p_alert_key text,
  p_alert_type text,
  p_severity text,
  p_active boolean,
  p_subject text,
  p_safe_detail jsonb
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, tw_internal
as $$
declare
  v_alert public.tw_ops_alerts%rowtype;
  v_id uuid;
  v_transition boolean := false;
begin
  select * into v_alert
  from public.tw_ops_alerts
  where alert_key=p_alert_key
  for update;

  if p_active then
    if v_alert.id is null then
      insert into public.tw_ops_alerts(
        alert_key,alert_type,severity,state,safe_detail,created_at,updated_at
      ) values (
        p_alert_key,p_alert_type,p_severity,'open',coalesce(p_safe_detail,'{}'::jsonb),now(),now()
      ) returning id into v_id;
      v_transition := true;
    else
      v_id := v_alert.id;
      v_transition := v_alert.state='resolved' or v_alert.severity is distinct from p_severity;
      update public.tw_ops_alerts
      set alert_type=p_alert_type,
          severity=p_severity,
          state=case when state='resolved' then 'open' else state end,
          safe_detail=coalesce(p_safe_detail,'{}'::jsonb),
          updated_at=now(),
          resolved_at=case when state='resolved' then null else resolved_at end
      where id=v_alert.id;
    end if;

    if v_transition and p_severity in ('high','critical') then
      insert into public.tw_ops_notification_outbox(
        notification_key,channel,event_type,severity,subject,safe_body,alert_id,state
      ) values (
        p_alert_key||':'||gen_random_uuid()::text,
        'external_pending','monitor_alert',p_severity,left(p_subject,160),
        left(coalesce(p_safe_detail,'{}'::jsonb)::text,2000),v_id,'pending'
      );
    end if;
  else
    if v_alert.id is not null and v_alert.state<>'resolved' then
      update public.tw_ops_alerts
      set state='resolved',resolved_at=now(),updated_at=now(),
          safe_detail=coalesce(p_safe_detail,'{}'::jsonb)
      where id=v_alert.id;
    end if;
    v_id := v_alert.id;
  end if;

  return v_id;
end;
$$;

revoke all on function tw_internal.upsert_monitor_alert(text,text,text,boolean,text,jsonb)
  from public,anon,authenticated;

create or replace function public.tw_ops_monitor_tick()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, tw_internal
as $$
declare
  v_run_id bigint;
  v_snapshot_id bigint;
  v_policy public.tw_ops_sla_policies%rowtype;
  v_policy_version text := 'fallback-internal';
  v_critical_ack integer := 15;
  v_high_ack integer := 60;
  v_support_response integer := 240;
  v_risk_review integer := 240;
  v_case_update integer := 1440;
  v_critical_overdue integer := 0;
  v_high_overdue integer := 0;
  v_support_overdue integer := 0;
  v_review_overdue integer := 0;
  v_stale_cases integer := 0;
  v_provider_failures integer := 0;
  v_stuck_provider_events integer := 0;
  v_stale_transfers integer := 0;
  v_stale_bill_payments integer := 0;
  v_unbalanced_journals integer := 0;
  v_critical_incidents integer := 0;
  v_major_incidents integer := 0;
  v_state text := 'healthy';
  v_counts jsonb;
  v_fingerprint text;
begin
  insert into public.tw_ops_monitor_runs(state)
  values ('running')
  returning id into v_run_id;

  select * into v_policy
  from public.tw_ops_sla_policies
  where active=true
  order by updated_at desc
  limit 1;

  if v_policy.id is not null then
    v_policy_version := v_policy.policy_version;
    v_critical_ack := v_policy.critical_alert_ack_minutes;
    v_high_ack := v_policy.high_alert_ack_minutes;
    v_support_response := v_policy.support_first_response_minutes;
    v_risk_review := v_policy.risk_review_minutes;
    v_case_update := v_policy.case_update_minutes;
  end if;

  select count(*) into v_critical_overdue
  from public.tw_ops_alerts
  where state='open' and severity='critical'
    and alert_type not in ('health_monitor','reconciliation')
    and created_at < now() - make_interval(mins=>v_critical_ack);

  select count(*) into v_high_overdue
  from public.tw_ops_alerts
  where state='open' and severity='high'
    and alert_type not in ('health_monitor','reconciliation')
    and created_at < now() - make_interval(mins=>v_high_ack);

  select count(*) into v_support_overdue
  from public.tw_support_requests
  where first_staff_response_at is null
    and state not in ('resolved','closed')
    and created_at < now() - make_interval(mins=>v_support_response);

  select count(*) into v_review_overdue
  from public.tw_risk_reviews
  where state='pending'
    and created_at < now() - make_interval(mins=>v_risk_review);

  select count(*) into v_stale_cases
  from public.tw_ops_cases
  where state not in ('resolved','closed')
    and updated_at < now() - make_interval(mins=>v_case_update);

  select count(*) into v_provider_failures
  from public.tw_money_provider_events
  where state='failed'
    and received_at >= now() - interval '15 minutes';

  select count(*) into v_stuck_provider_events
  from public.tw_money_provider_events
  where state in ('received','processing')
    and received_at < now() - interval '10 minutes';

  select count(*) into v_stale_transfers
  from public.tw_money_transfers
  where state in ('authorized','submitted','pending')
    and updated_at < now() - interval '24 hours';

  select count(*) into v_stale_bill_payments
  from public.tw_money_bill_payments
  where state in ('authorized','scheduled','submitted','processing')
    and updated_at < now() - interval '24 hours';

  select count(*) into v_unbalanced_journals
  from (
    select journal_id from public.tw_money_ledger_entries
    group by journal_id having sum(amount_cents)<>0
  ) q;

  select count(*) into v_critical_incidents
  from public.tw_ops_incidents
  where state<>'resolved' and severity='critical';

  select count(*) into v_major_incidents
  from public.tw_ops_incidents
  where state<>'resolved' and severity='major';

  if v_unbalanced_journals>0
     or v_critical_overdue>0
     or v_critical_incidents>0
     or v_provider_failures>=5
     or v_stuck_provider_events>=5 then
    v_state := 'critical';
  elsif v_high_overdue>0
     or v_support_overdue>0
     or v_review_overdue>0
     or v_stale_cases>0
     or v_provider_failures>0
     or v_stuck_provider_events>0
     or v_stale_transfers>0
     or v_stale_bill_payments>0
     or v_major_incidents>0 then
    v_state := 'degraded';
  end if;

  v_counts := jsonb_build_object(
    'criticalOverdue',v_critical_overdue,
    'highOverdue',v_high_overdue,
    'supportOverdue',v_support_overdue,
    'reviewOverdue',v_review_overdue,
    'staleCases',v_stale_cases,
    'providerFailures15m',v_provider_failures,
    'stuckProviderEvents',v_stuck_provider_events,
    'staleTransfers24h',v_stale_transfers,
    'staleBillPayments24h',v_stale_bill_payments,
    'unbalancedJournals',v_unbalanced_journals,
    'criticalIncidents',v_critical_incidents,
    'majorIncidents',v_major_incidents
  );

  v_fingerprint := md5(v_state||':'||v_counts::text);

  insert into public.tw_ops_health_snapshots(
    health_state,policy_version,counts,fingerprint
  ) values (v_state,v_policy_version,v_counts,v_fingerprint)
  returning id into v_snapshot_id;

  perform tw_internal.upsert_monitor_alert(
    'monitor:ledger_unbalanced','reconciliation','critical',
    v_unbalanced_journals>0,'Ledger balance invariant failed',
    jsonb_build_object('count',v_unbalanced_journals,'monitorRunId',v_run_id)
  );

  perform tw_internal.upsert_monitor_alert(
    'monitor:provider_event_failures','health_monitor',
    case when v_provider_failures>=5 then 'critical' else 'high' end,
    v_provider_failures>0,'Provider events are failing',
    jsonb_build_object('count15m',v_provider_failures,'monitorRunId',v_run_id)
  );

  perform tw_internal.upsert_monitor_alert(
    'monitor:stuck_provider_events','health_monitor',
    case when v_stuck_provider_events>=5 then 'critical' else 'high' end,
    v_stuck_provider_events>0,'Provider events are stuck',
    jsonb_build_object('count',v_stuck_provider_events,'ageThresholdMinutes',10,'monitorRunId',v_run_id)
  );

  perform tw_internal.upsert_monitor_alert(
    'monitor:stale_money_operations','reconciliation','high',
    (v_stale_transfers+v_stale_bill_payments)>0,
    'Money operations need reconciliation',
    jsonb_build_object('staleTransfers24h',v_stale_transfers,'staleBillPayments24h',v_stale_bill_payments,'monitorRunId',v_run_id)
  );

  perform tw_internal.upsert_monitor_alert(
    'monitor:operations_sla','health_monitor',
    case when v_critical_overdue>0 then 'critical' else 'high' end,
    (v_critical_overdue+v_high_overdue+v_support_overdue+v_review_overdue+v_stale_cases)>0,
    'Operations queue has overdue work',
    jsonb_build_object(
      'criticalOverdue',v_critical_overdue,'highOverdue',v_high_overdue,
      'supportOverdue',v_support_overdue,'reviewOverdue',v_review_overdue,
      'staleCases',v_stale_cases,'monitorRunId',v_run_id
    )
  );

  perform tw_internal.upsert_monitor_alert(
    'monitor:active_incidents','health_monitor',
    case when v_critical_incidents>0 then 'critical' else 'high' end,
    (v_critical_incidents+v_major_incidents)>0,
    'Major or critical incidents are active',
    jsonb_build_object('criticalIncidents',v_critical_incidents,'majorIncidents',v_major_incidents,'monitorRunId',v_run_id)
  );

  update public.tw_ops_monitor_runs
  set state='succeeded',snapshot_id=v_snapshot_id,
      safe_detail=jsonb_build_object('healthState',v_state,'counts',v_counts),
      finished_at=now()
  where id=v_run_id;

  return jsonb_build_object(
    'runId',v_run_id,'snapshotId',v_snapshot_id,'healthState',v_state,
    'policyVersion',v_policy_version,'counts',v_counts
  );
exception when others then
  if v_run_id is not null then
    update public.tw_ops_monitor_runs
    set state='failed',
        safe_detail=jsonb_build_object('errorCode',left(SQLSTATE||':'||SQLERRM,500)),
        finished_at=now()
    where id=v_run_id;
  end if;
  raise;
end;
$$;

revoke all on function public.tw_ops_monitor_tick()
  from public,anon,authenticated;
grant execute on function public.tw_ops_monitor_tick()
  to service_role;

select cron.schedule(
  'thisweek-phase29-health-monitor',
  '*/5 * * * *',
  'select public.tw_ops_monitor_tick();'
);

commit;
