-- Phase 31 — Production Activation Interlock
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Environment flags and provider credentials are necessary but never sufficient for live money.

begin;

create table if not exists public.tw_release_gates (
  gate_key text primary key,
  category text not null
    check (category in ('auth','providers','risk','operations','legal','commercial')),
  label text not null,
  required_for_live_money boolean not null default true,
  verified boolean not null default false,
  verified_by_staff_user_id uuid references auth.users(id) on delete set null,
  verified_at timestamptz,
  evidence_ref text,
  note text,
  updated_at timestamptz not null default now()
);

create table if not exists public.tw_release_gate_events (
  id bigint generated by default as identity primary key,
  gate_key text not null references public.tw_release_gates(gate_key) on delete restrict,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  previous_verified boolean not null,
  next_verified boolean not null,
  evidence_ref text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.tw_release_gates enable row level security;
alter table public.tw_release_gate_events enable row level security;
revoke all on table public.tw_release_gates,public.tw_release_gate_events from public,anon,authenticated;
grant select,insert,update,delete on table public.tw_release_gates to service_role;
grant select,insert on table public.tw_release_gate_events to service_role;
grant usage,select on sequence public.tw_release_gate_events_id_seq to service_role;

drop trigger if exists tw_release_gate_events_immutable on public.tw_release_gate_events;
create trigger tw_release_gate_events_immutable
before update or delete on public.tw_release_gate_events
for each row execute function tw_internal.reject_money_history_mutation();

insert into public.tw_release_gates(gate_key,category,label,required_for_live_money,verified)
values
  ('hosted_auth_production_ready','auth','Hosted Auth production configuration verified',true,false),
  ('provider_sandbox_e2e_passed','providers','Provider Sandbox chain passed end-to-end',true,false),
  ('production_provider_approvals','providers','Provider / banking program production approvals complete',true,false),
  ('production_webhooks_verified','providers','Production provider webhook registrations verified',true,false),
  ('production_risk_policy_approved','risk','Production risk limits reviewed and approved',true,false),
  ('named_staff_provisioned','operations','Named least-privilege staff coverage provisioned',true,false),
  ('external_notification_delivery_verified','operations','External critical notification delivery tested',true,false),
  ('incident_escalation_runbook_approved','operations','Incident and provider escalation runbook approved',true,false),
  ('retention_access_policy_approved','legal','Retention and access-log policy approved',true,false),
  ('legal_terms_privacy_approved','legal','Customer terms, privacy, disclosures and authorizations approved',true,false),
  ('cost_approval','commercial','Provider/program production costs explicitly approved',true,false)
on conflict (gate_key) do update set
  category=excluded.category,
  label=excluded.label,
  required_for_live_money=excluded.required_for_live_money;

create or replace function public.tw_release_status()
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  with manual as (
    select
      coalesce(bool_and(verified) filter (where required_for_live_money),false) as manual_ready,
      coalesce(
        jsonb_agg(
          jsonb_build_object(
            'gateKey',gate_key,
            'category',category,
            'label',label,
            'required',required_for_live_money,
            'verified',verified,
            'verifiedAt',verified_at,
            'evidenceRef',evidence_ref,
            'note',note
          ) order by category,gate_key
        ),
        '[]'::jsonb
      ) as gates
    from public.tw_release_gates
  ),
  derived as (
    select
      exists(select 1 from public.tw_risk_policies where environment='production' and active=true)
        as production_risk_active,
      exists(
        select 1 from public.tw_ops_notification_channel_status
        where channel_key='external_webhook' and configured=true and state='healthy'
      ) as notification_channel_healthy,
      exists(
        select 1 from auth.users
        where coalesce(raw_app_meta_data->>'thisweek_role','')='admin'
      ) as admin_staff_exists,
      exists(
        select 1 from auth.users
        where coalesce(raw_app_meta_data->>'thisweek_role','') in ('risk_ops','admin')
      ) as risk_staff_exists,
      exists(
        select 1 from auth.users
        where coalesce(raw_app_meta_data->>'thisweek_role','') in ('support_ops','admin')
      ) as support_staff_exists
  )
  select jsonb_build_object(
    'manualGatesReady',manual.manual_ready,
    'productionRiskPolicyActive',derived.production_risk_active,
    'notificationChannelHealthy',derived.notification_channel_healthy,
    'staffCoverage',jsonb_build_object(
      'admin',derived.admin_staff_exists,
      'risk',derived.risk_staff_exists,
      'support',derived.support_staff_exists
    ),
    'liveMoneyReady',
      manual.manual_ready
      and derived.production_risk_active
      and derived.notification_channel_healthy
      and derived.admin_staff_exists
      and derived.risk_staff_exists
      and derived.support_staff_exists,
    'gates',manual.gates
  )
  from manual cross join derived;
$$;

create or replace function public.tw_release_money_enabled()
returns boolean
language sql
security definer
stable
set search_path = pg_catalog, public, auth
as $$
  select coalesce((public.tw_release_status()->>'liveMoneyReady')::boolean,false);
$$;

create or replace function public.tw_release_set_gate(
  p_staff_user_id uuid,
  p_gate_key text,
  p_verified boolean,
  p_evidence_ref text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_gate public.tw_release_gates%rowtype;
  v_role text;
begin
  select coalesce(raw_app_meta_data->>'thisweek_role','')
  into v_role
  from auth.users
  where id=p_staff_user_id;

  if v_role is distinct from 'admin' then
    raise exception 'admin_role_required';
  end if;

  select * into v_gate
  from public.tw_release_gates
  where gate_key=p_gate_key
  for update;

  if v_gate.gate_key is null then raise exception 'release_gate_not_found'; end if;
  if coalesce(length(trim(p_evidence_ref)),0)<3 then raise exception 'release_gate_evidence_required'; end if;

  insert into public.tw_release_gate_events(
    gate_key,staff_user_id,previous_verified,next_verified,evidence_ref,note
  ) values (
    v_gate.gate_key,p_staff_user_id,v_gate.verified,p_verified,
    left(trim(p_evidence_ref),500),left(nullif(trim(coalesce(p_note,'')),''),1000)
  );

  update public.tw_release_gates
  set verified=p_verified,
      verified_by_staff_user_id=p_staff_user_id,
      verified_at=case when p_verified then now() else null end,
      evidence_ref=left(trim(p_evidence_ref),500),
      note=left(nullif(trim(coalesce(p_note,'')),''),1000),
      updated_at=now()
  where gate_key=v_gate.gate_key;

  return jsonb_build_object(
    'gateKey',v_gate.gate_key,
    'verified',p_verified,
    'updatedBy',p_staff_user_id,
    'updatedAt',now()
  );
end;
$$;

revoke all on function public.tw_release_status() from public,anon,authenticated;
revoke all on function public.tw_release_money_enabled() from public,anon,authenticated;
revoke all on function public.tw_release_set_gate(uuid,text,boolean,text,text) from public,anon,authenticated;
grant execute on function public.tw_release_status() to service_role;
grant execute on function public.tw_release_money_enabled() to service_role;
grant execute on function public.tw_release_set_gate(uuid,text,boolean,text,text) to service_role;

commit;
