-- Phase 32 — Legal Consent, Retention & Sensitive-Access Audit
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Production legal and retention rows are deliberately inactive/unapproved.

begin;

create table if not exists public.tw_legal_documents (
  id uuid primary key default gen_random_uuid(),
  environment text not null check (environment in ('sandbox','production')),
  document_key text not null,
  document_type text not null check (document_type in ('terms','privacy','esign','ach_authorization','card_disclosure','reward_terms','other')),
  version text not null,
  title text not null,
  public_path text not null,
  content_sha256 text not null check (content_sha256 ~ '^[0-9a-f]{64}$'),
  required_for_money boolean not null default false,
  active boolean not null default false,
  approved_for_use boolean not null default false,
  approved_by_staff_user_id uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  evidence_ref text,
  effective_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(environment,document_key,version)
);

create table if not exists public.tw_legal_acceptances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  legal_document_id uuid not null references public.tw_legal_documents(id) on delete restrict,
  session_id uuid,
  affirmation text not null,
  accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(user_id,legal_document_id)
);

create table if not exists public.tw_retention_policies (
  id uuid primary key default gen_random_uuid(),
  environment text not null check (environment in ('sandbox','production')),
  policy_version text not null,
  data_class text not null,
  retention_days integer check (retention_days is null or retention_days >= 0),
  disposition text not null check (disposition in ('delete','pseudonymize','review_required','retain_legal')),
  active boolean not null default false,
  approved_for_use boolean not null default false,
  approved_by_staff_user_id uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  evidence_ref text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(environment,policy_version,data_class)
);

create table if not exists public.tw_sensitive_access_events (
  id bigint generated by default as identity primary key,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  staff_role text not null check (staff_role in ('support_ops','risk_ops','admin')),
  session_id uuid,
  action text not null,
  resource_type text not null,
  resource_ref text not null,
  subject_user_id uuid,
  data_classes text[] not null default '{}',
  reason_code text,
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.tw_legal_documents enable row level security;
alter table public.tw_legal_acceptances enable row level security;
alter table public.tw_retention_policies enable row level security;
alter table public.tw_sensitive_access_events enable row level security;

revoke all on table public.tw_legal_documents,public.tw_legal_acceptances,public.tw_retention_policies,public.tw_sensitive_access_events
  from public,anon,authenticated;
grant select,insert,update,delete on table public.tw_legal_documents,public.tw_legal_acceptances,public.tw_retention_policies to service_role;
grant select,insert on table public.tw_sensitive_access_events to service_role;
grant usage,select on sequence public.tw_sensitive_access_events_id_seq to service_role;

drop trigger if exists tw_legal_acceptances_immutable on public.tw_legal_acceptances;
create trigger tw_legal_acceptances_immutable before update or delete on public.tw_legal_acceptances
for each row execute function tw_internal.reject_money_history_mutation();

drop trigger if exists tw_sensitive_access_events_immutable on public.tw_sensitive_access_events;
create trigger tw_sensitive_access_events_immutable before update or delete on public.tw_sensitive_access_events
for each row execute function tw_internal.reject_money_history_mutation();

-- Sandbox-only fixtures are active so acceptance can be tested.
insert into public.tw_legal_documents(environment,document_key,document_type,version,title,public_path,content_sha256,required_for_money,active,approved_for_use,effective_at)
values
('sandbox','terms_of_service','terms','sandbox-2026-09','Sandbox Terms Test','https://bennybundles.github.io/Thisweekmvp/legal/sandbox/#terms',encode(digest('thisweek-sandbox-terms-2026-09','sha256'),'hex'),true,true,true,now()),
('sandbox','privacy_policy','privacy','sandbox-2026-09','Sandbox Privacy Test','https://bennybundles.github.io/Thisweekmvp/legal/sandbox/#privacy',encode(digest('thisweek-sandbox-privacy-2026-09','sha256'),'hex'),true,true,true,now()),
('sandbox','esign_consent','esign','sandbox-2026-09','Sandbox E-Sign Test','https://bennybundles.github.io/Thisweekmvp/legal/sandbox/#esign',encode(digest('thisweek-sandbox-esign-2026-09','sha256'),'hex'),true,true,true,now()),
('sandbox','ach_authorization','ach_authorization','sandbox-2026-09','Sandbox ACH Authorization Test','https://bennybundles.github.io/Thisweekmvp/legal/sandbox/#ach',encode(digest('thisweek-sandbox-ach-2026-09','sha256'),'hex'),true,true,true,now()),
('sandbox','cardholder_disclosure','card_disclosure','sandbox-2026-09','Sandbox Card Disclosure Test','https://bennybundles.github.io/Thisweekmvp/legal/sandbox/#card',encode(digest('thisweek-sandbox-card-2026-09','sha256'),'hex'),true,true,true,now())
on conflict (environment,document_key,version) do nothing;

-- Production templates are intentionally not active/approved.
insert into public.tw_legal_documents(environment,document_key,document_type,version,title,public_path,content_sha256,required_for_money,active,approved_for_use)
values
('production','terms_of_service','terms','production-template-2026-09','Production Terms','https://bennybundles.github.io/Thisweekmvp/legal/terms/',encode(digest('production-terms-not-approved','sha256'),'hex'),true,false,false),
('production','privacy_policy','privacy','production-template-2026-09','Production Privacy Policy','https://bennybundles.github.io/Thisweekmvp/legal/privacy/',encode(digest('production-privacy-not-approved','sha256'),'hex'),true,false,false),
('production','esign_consent','esign','production-template-2026-09','Production E-Sign Consent','https://bennybundles.github.io/Thisweekmvp/legal/esign/',encode(digest('production-esign-not-approved','sha256'),'hex'),true,false,false),
('production','ach_authorization','ach_authorization','production-template-2026-09','Production ACH Authorization','https://bennybundles.github.io/Thisweekmvp/legal/ach/',encode(digest('production-ach-not-approved','sha256'),'hex'),true,false,false),
('production','cardholder_disclosure','card_disclosure','production-template-2026-09','Production Cardholder Disclosure','https://bennybundles.github.io/Thisweekmvp/legal/card/',encode(digest('production-card-not-approved','sha256'),'hex'),true,false,false)
on conflict (environment,document_key,version) do nothing;

insert into public.tw_retention_policies(environment,policy_version,data_class,retention_days,disposition,active,approved_for_use,note)
select 'sandbox','2026-09-sandbox-v1',x.data_class,x.retention_days,'review_required',true,true,
       'Sandbox retention test policy only; no automatic destructive deletion.'
from (values
('financial_ledger',null::integer),('provider_events',90),('support_records',365),('staff_access',365),
('auth_security',180),('legal_acceptance',null::integer),('ops_records',365)
) x(data_class,retention_days)
on conflict (environment,policy_version,data_class) do nothing;

insert into public.tw_retention_policies(environment,policy_version,data_class,retention_days,disposition,active,approved_for_use,note)
select 'production','production-template-2026-09',x.data_class,x.retention_days,x.disposition,false,false,
       'Production template. Requires legal/compliance approval before activation.'
from (values
('financial_ledger',null::integer,'retain_legal'),('provider_events',null::integer,'review_required'),
('support_records',null::integer,'review_required'),('staff_access',null::integer,'review_required'),
('auth_security',null::integer,'review_required'),('legal_acceptance',null::integer,'retain_legal'),
('ops_records',null::integer,'review_required')
) x(data_class,retention_days,disposition)
on conflict (environment,policy_version,data_class) do nothing;

-- Service-role-only RPCs deployed by this migration:
-- tw_legal_status(uuid,text)
-- tw_user_production_legal_ready(uuid)
-- tw_legal_accept_document(uuid,uuid,uuid,text)
-- tw_retention_status(text)
-- tw_sensitive_access_record(uuid,text,uuid,text,text,text,uuid,text[],text,jsonb)
-- tw_legal_set_document_state(uuid,uuid,boolean,boolean,text,text)
-- tw_retention_set_policy_state(uuid,uuid,boolean,boolean,text,text)
--
-- tw_release_status() was replaced so liveMoneyReady additionally requires:
--   productionLegalSetActive
--   productionRetentionPolicyActive
--   sensitiveAccessAuditActive

revoke all on function public.tw_legal_status(uuid,text) from public,anon,authenticated;
revoke all on function public.tw_user_production_legal_ready(uuid) from public,anon,authenticated;
revoke all on function public.tw_legal_accept_document(uuid,uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.tw_retention_status(text) from public,anon,authenticated;
revoke all on function public.tw_sensitive_access_record(uuid,text,uuid,text,text,text,uuid,text[],text,jsonb) from public,anon,authenticated;
revoke all on function public.tw_legal_set_document_state(uuid,uuid,boolean,boolean,text,text) from public,anon,authenticated;
revoke all on function public.tw_retention_set_policy_state(uuid,uuid,boolean,boolean,text,text) from public,anon,authenticated;

grant execute on function public.tw_legal_status(uuid,text) to service_role;
grant execute on function public.tw_user_production_legal_ready(uuid) to service_role;
grant execute on function public.tw_legal_accept_document(uuid,uuid,uuid,text) to service_role;
grant execute on function public.tw_retention_status(text) to service_role;
grant execute on function public.tw_sensitive_access_record(uuid,text,uuid,text,text,text,uuid,text[],text,jsonb) to service_role;
grant execute on function public.tw_legal_set_document_state(uuid,uuid,boolean,boolean,text,text) to service_role;
grant execute on function public.tw_retention_set_policy_state(uuid,uuid,boolean,boolean,text,text) to service_role;

commit;
