const SUPABASE_URL='https://xjtvawmppzwzrooairyx.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_OcmV-NiXzSy7mqg3TUKxnA_74l8fq87';
const SESSION_KEY='thisweek.auth.session.v1';
const $=id=>document.getElementById(id);
let session=readSession(),user=null,dashboardData=null;

function readSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
function writeSession(next){session=next?.access_token?{access_token:next.access_token,refresh_token:next.refresh_token||session?.refresh_token||null,expires_at:next.expires_at||Math.floor(Date.now()/1000)+(next.expires_in||3600)}:null;if(session)sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));else sessionStorage.removeItem(SESSION_KEY);updateUi();}
function jwtPayload(token){try{const p=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(p.padEnd(Math.ceil(p.length/4)*4,'=')));}catch{return{};}}
function headers(auth=false){const h={'apikey':PUBLISHABLE_KEY,'Content-Type':'application/json'};if(auth&&session?.access_token)h.Authorization='Bearer '+session.access_token;return h;}
async function api(path,options={}){const r=await fetch(SUPABASE_URL+path,{...options,headers:{...headers(!!options.auth),...(options.headers||{})}});const text=await r.text();let b={};try{b=text?JSON.parse(text):{};}catch{b={raw:text};}if(!r.ok)throw new Error(b.msg||b.message||b.error_description||b.error||('HTTP '+r.status));return b;}
async function ensureFresh(){if(!session?.refresh_token)return false;if((session.expires_at||0)-Math.floor(Date.now()/1000)>90)return true;const b=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});writeSession(b);return true;}
async function getUser(){if(!session?.access_token){user=null;updateUi();renderFactors();return null;}await ensureFresh();user=await api('/auth/v1/user',{method:'GET',auth:true});updateUi();renderFactors();return user;}
function setResult(id,text,kind=''){const el=$(id);el.textContent=text||'';el.className='result '+kind;}
function updateUi(){const p=session?.access_token?jwtPayload(session.access_token):{};$('sessionState').textContent=session?'Signed in':'Signed out';$('aalState').textContent=p.aal||'—';$('signOut').disabled=!session;$('verifyMfa').disabled=!session;$('refresh').disabled=!session;$('applyControl').disabled=!session;}
function renderFactors(){const el=$('factorSelect');el.textContent='';const factors=Array.isArray(user?.factors)?user.factors.filter(x=>x.status==='verified'):[];if(!factors.length){const o=document.createElement('option');o.value='';o.textContent='No verified factor';el.appendChild(o);return;}for(const f of factors){const o=document.createElement('option');o.value=f.id;o.textContent=(f.friendly_name||'TOTP')+' · '+f.status;el.appendChild(o);}}
async function signIn(){const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<10)throw new Error('Enter staff email and password.');const b=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});writeSession(b);$('password').value='';await getUser();setResult('authResult','Signed in. Verify MFA to open staff operations.','good');await refreshDashboard().catch(e=>setResult('authResult',e.message,'warn'));}
async function signOut(){if(session)try{await api('/auth/v1/logout?scope=local',{method:'POST',auth:true,body:'{}'});}catch{}writeSession(null);user=null;dashboardData=null;renderFactors();clearDashboard();setResult('authResult','Signed out.','good');}
async function verifyMfa(){await ensureFresh();const factorId=$('factorSelect').value,code=$('totpCode').value.trim();if(!factorId||!/^[0-9]{6,8}$/.test(code))throw new Error('Choose a verified factor and enter its current code.');const ch=await api('/auth/v1/factors/'+encodeURIComponent(factorId)+'/challenge',{method:'POST',auth:true,body:'{}'});const v=await api('/auth/v1/factors/'+encodeURIComponent(factorId)+'/verify',{method:'POST',auth:true,body:JSON.stringify({challenge_id:ch.id,code})});if(v.access_token)writeSession(v);$('totpCode').value='';await getUser();setResult('mfaResult','MFA verified.','good');await refreshDashboard();}
async function ops(action,extra={}){await ensureFresh();const r=await fetch(SUPABASE_URL+'/functions/v1/thisweek-ops-gateway',{method:'POST',headers:{'apikey':PUBLISHABLE_KEY,'Authorization':'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const text=await r.text();let b={};try{b=text?JSON.parse(text):{};}catch{b={raw:text};}if(!r.ok)throw new Error(b.error||('Ops Gateway HTTP '+r.status));return b;}
function clearDashboard(){$('roleState').textContent='—';$('alertCount').textContent='—';$('reviewCount').textContent='—';for(const id of ['alerts','reviews','cases']){$(id).textContent='';const e=document.createElement('div');e.className='empty';e.textContent='No data loaded.';$(id).appendChild(e);}$('audit').textContent='';const e=document.createElement('div');e.className='empty';e.textContent='No audit data loaded.';$('audit').appendChild(e);}
function badge(text,severity='medium'){const s=document.createElement('span');s.className='badge '+severity;s.textContent=text;return s;}
function money(cents){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(cents||0)/100);}
function button(label,fn,cls=''){const b=document.createElement('button');b.textContent=label;if(cls)b.className=cls;b.addEventListener('click',()=>fn().catch(e=>setResult('authResult',e.message,'bad')));return b;}
function itemBase(kicker,title,severity='medium'){const wrap=document.createElement('div');wrap.className='item';const head=document.createElement('div');head.className='item-head';const copy=document.createElement('div');const sm=document.createElement('small');sm.textContent=kicker;const st=document.createElement('strong');st.textContent=title;copy.append(sm,st);head.append(copy,badge(severity,severity));wrap.appendChild(head);return wrap;}
function renderAlerts(rows){const root=$('alerts');root.textContent='';if(!rows.length){const e=document.createElement('div');e.className='empty';e.textContent='No open alerts.';root.appendChild(e);return;}for(const x of rows){const item=itemBase(x.alert_type||'Alert',(x.user_id||'user')+' · '+(x.state||'open'),x.severity||'medium');const p=document.createElement('p');p.textContent='Created '+new Date(x.created_at).toLocaleString()+(x.case_id?' · case '+x.case_id:'')+(x.risk_review_id?' · review '+x.risk_review_id:'');item.appendChild(p);if(x.state==='open')item.appendChild(button('Acknowledge',async()=>{await ops('ack_alert',{alertId:x.id});await refreshDashboard();},'primary'));root.appendChild(item);}}
function renderReviews(rows,role){const root=$('reviews');root.textContent='';if(!rows.length){const e=document.createElement('div');e.className='empty';e.textContent='No pending risk reviews.';root.appendChild(e);return;}for(const r of rows){const ev=r.riskEvent||{};const item=itemBase('Risk review '+r.id,(ev.action||'risk action')+' · '+money(ev.amount_cents),'high');const p=document.createElement('p');p.textContent='User '+r.user_id+' · '+(ev.reason_code||'manual review')+' · '+new Date(r.created_at).toLocaleString();item.appendChild(p);const controls=document.createElement('div');controls.className='controls';const reason=document.createElement('input');reason.placeholder='resolution reason';const note=document.createElement('input');note.placeholder='optional note';controls.append(reason,note);const action=document.createElement('div');action.className='actions';const allowed=role==='risk_ops'||role==='admin';const approve=button('Approve',async()=>{if(!reason.value.trim())throw new Error('Enter a resolution reason.');await ops('resolve_risk_review',{reviewId:r.id,resolution:'approved',reasonCode:reason.value.trim(),note:note.value.trim()});await refreshDashboard();},'primary');const deny=button('Deny',async()=>{if(!reason.value.trim())throw new Error('Enter a resolution reason.');await ops('resolve_risk_review',{reviewId:r.id,resolution:'denied',reasonCode:reason.value.trim(),note:note.value.trim()});await refreshDashboard();},'danger');approve.disabled=deny.disabled=!allowed;action.append(approve,deny);item.append(controls,action);root.appendChild(item);}}
function renderCases(rows){const root=$('cases');root.textContent='';if(!rows.length){const e=document.createElement('div');e.className='empty';e.textContent='No open operational cases.';root.appendChild(e);return;}for(const c of rows){const item=itemBase(c.case_type||'Case',(c.user_id||'user')+' · '+(c.state||'open'),c.severity||'medium');const p=document.createElement('p');p.textContent=(c.provider||'internal')+' · '+(c.reason_code||'no reason')+' · '+(c.amount_cents==null?'no amount':money(c.amount_cents))+(c.assigned_to_staff_user_id?' · assigned':' · unassigned');item.appendChild(p);const controls=document.createElement('div');controls.className='controls';const state=document.createElement('select');for(const v of ['monitoring','action_required','resolved','closed']){const o=document.createElement('option');o.value=v;o.textContent=v.replaceAll('_',' ');state.appendChild(o);}state.value=c.state==='open'?'monitoring':c.state;const reason=document.createElement('input');reason.placeholder='resolution reason';const note=document.createElement('input');note.placeholder='bounded staff note';controls.append(state,reason,note);const action=document.createElement('div');action.className='actions';action.append(button('Assign to me',async()=>{await ops('assign_case',{caseId:c.id});await refreshDashboard();}),button('Update case',async()=>{if(!reason.value.trim())throw new Error('Enter a reason.');await ops('resolve_case',{caseId:c.id,state:state.value,reasonCode:reason.value.trim(),note:note.value.trim()});await refreshDashboard();},'primary'),button('Use user ID',async()=>{$('controlUserId').value=c.user_id;}));item.append(controls,action);root.appendChild(item);}}
function renderAudit(rows){const root=$('audit');root.textContent='';if(!rows.length){const e=document.createElement('div');e.className='empty';e.textContent='No staff actions recorded.';root.appendChild(e);return;}for(const x of rows){const r=document.createElement('div');r.className='audit-row';const strong=document.createElement('strong');strong.textContent=(x.action||'action')+' · '+(x.staff_role||'role');const text=document.createTextNode(' — '+(x.target_type||'target')+' '+(x.target_ref||'')+' · '+new Date(x.created_at).toLocaleString()+(x.reason_code?' · '+x.reason_code:''));r.append(strong,text);root.appendChild(r);}}
async function refreshDashboard(){const d=await ops('dashboard');dashboardData=d;$('roleState').textContent=d.staff?.role||'—';$('alertCount').textContent=String(d.alerts?.length||0);$('reviewCount').textContent=String(d.riskReviews?.length||0);renderAlerts(d.alerts||[]);renderReviews(d.riskReviews||[],d.staff?.role||'');renderCases(d.cases||[]);renderAudit(d.recentStaffActions||[]);setResult('authResult','Operations data refreshed.','good');return d;}
async function applyControl(){const userId=$('controlUserId').value.trim(),state=$('controlState').value,reason=$('controlReason').value.trim();if(!userId)throw new Error('Enter a user ID.');if(state!=='normal'&&!reason)throw new Error('Enter a control reason.');const d=await ops('set_user_control',{userId,state,reasonCode:reason||'control_cleared'});setResult('controlResult','Control updated: '+(d.result?.state||state)+'.','good');await refreshDashboard();}
function bind(id,fn){$(id).addEventListener('click',()=>fn().catch(e=>setResult(id==='verifyMfa'?'mfaResult':id==='applyControl'?'controlResult':'authResult',e.message,'bad')));}
bind('signIn',signIn);bind('signOut',signOut);bind('verifyMfa',verifyMfa);bind('refresh',refreshDashboard);bind('applyControl',applyControl);
updateUi();clearDashboard();if(session?.access_token)getUser().then(()=>refreshDashboard()).catch(e=>setResult('authResult',e.message,'warn'));
