-- Phase 33 — Cloud Data Export & Privacy Inventory
-- Applied to Supabase project xjtvawmppzwzrooairyx on 2026-09-19.
-- Export payloads are assembled client-side; the server stores only append-only export audit events.

begin;

create table if not exists public.tw_privacy_export_events (
  id bigint generated by default as identity primary key,
  export_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('started','completed','failed')),
  format text not null default 'json' check (format in ('json')),
  dataset_count integer check (dataset_count is null or dataset_count >= 0),
  record_count bigint check (record_count is null or record_count >= 0),
  safe_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists tw_privacy_export_events_user_idx
  on public.tw_privacy_export_events(user_id,created_at desc);
create index if not exists tw_privacy_export_events_export_idx
  on public.tw_privacy_export_events(export_id,id);

alter table public.tw_privacy_export_events enable row level security;
revoke all on table public.tw_privacy_export_events from public,anon,authenticated;
grant select,insert on table public.tw_privacy_export_events to service_role;
grant usage,select on sequence public.tw_privacy_export_events_id_seq to service_role;

drop trigger if exists tw_privacy_export_events_immutable on public.tw_privacy_export_events;
create trigger tw_privacy_export_events_immutable
before update or delete on public.tw_privacy_export_events
for each row execute function tw_internal.reject_money_history_mutation();

comment on table public.tw_privacy_export_events is
  'Append-only self-service cloud-export audit. This table never stores the export payload or provider secrets.';

commit;
